### ISSUE TITLE
Delete user account - delete account backend work

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1010]
Speed up / make the account deletion progress easier by writing scripts to automate deletion.

## References
- https://github.com/techmatters/terraso-product/issues/418
- [Product Spec](https://docs.google.com/document/d/18t3V8KWm1wft7K66f91wwKfUQdwIQqJonFJszGaHGeM/edit#heading=h.54w02ys7n8ko)

### Tasks
- [ ] https://github.com/techmatters/terraso-backend/issues/1346

## Acceptance Criteria
- [ ] Write a script that allows staff members to complete deletion. Script should
  - [ ] delete the user account
     - [ ] delete unaffiliated sites
     - [ ] delete projects and affiliated sites where the user is the sole manager
  - [ ] Use the hubspot template to inform the user their account has been deleted - [Delete Account Email Template](https://app.hubspot.com/templates/9151742)

- [ ] Deletion should not delete Terraso identity and things associated with it (story maps, shared files, groups, etc).
- [ ] Deletion should not remove the name of the user from notes attached to projects (or the future audit log).
