### ISSUE TITLE
Usability tests for September

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#1011]
An unmoderated test on UserTesting. I could send it out to all of our people who have shown willingness to test things. Being unmoderated means they can do it on their own time, which will hopefully be helpful in terms of recruitment. I'm thinking of creating a group in Hubspot for these people that we can send an email to with the request. As we seek other testers we can add them to the group as well. Then, in the UserTesting platform I can group all of them that sign up in a "Contributor Network". Depending on the test design, we could also pull from User Testing's pool. 

Site Creation short test
- unmoderated prototype
- get a mix of existing LandPKS users, non-users, and UserTesting recruits

```[tasklist]
### Tasks
- [x] Synthesize data from August FIUT and present to team
- [x] Create tasks from FIUT Mural actions
- [ ] Outreach to David Kmiti
- [x] Outreach to UNCA
```

```[tasklist]
### Unmoderated Test
- [x] Build prototype
- [x] Create test plan
- [ ] Build test
- [ ] Run pilot
```

**Comment by CourtneyLee333** [comment]
Moved unfinished tasks to October sprint.
