### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1044]
This issue captures a collection of tasks we're going to do around improving accessibility in LandPKS.

```[tasklist]
### Tasks
- [ ] SINA/PAC reviews LandPKS
- [ ] Recommendations by consultant
- [ ] Recommendations by consultant
- [ ] Recommendations by consultant
```
