### ISSUE TITLE
Write Documentation - Add Team Members

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1067]
[Add team members](https://docs.google.com/document/d/1iuCa1lc470pmQHvHL4hoK2mm8luVPiz-0QhJDgInNKg/edit)

```[tasklist]
### Tasks
- [ ] Laura writes initial content
- [ ] Derek finishes add team members
- [ ] Paul Reviews
- [ ] copy to landpks.terraso.org
```

**Comment by DerekCaelin** [comment]
This is already done: https://landpks.terraso.org/help/teams/
