### ISSUE TITLE
Design template for Article/Resource

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1111]
EG: https://docs.google.com/document/d/1Z8skSfrAXh71iK0fhn5zahzVTbP05cl2_TpDaHglfm0/edit#heading=h.hcwj6t7yg47u

[Article post template](https://landpks.terraso.org/what-is-soil-id-and-why-does-it-matter/)
[Post archive template](https://landpks.terraso.org/tag/intro-series/) (for all post types)
[Articles & Resources archive template](https://landpks.terraso.org/category/article/)
[Article card element for pages](https://landpks.terraso.org/help/soil-id-and-ecological-site/) see example "Related Reading" at bottom of the page
[Article sidebar navigation](https://landpks.terraso.org/wp-admin/post.php?post=1770&action=edit) for future use (it's hidden now)
[Documentation for website admins](https://docs.google.com/document/d/1ilmHSeIl6wX1ORZQX_ZsrAi56IzpYCxnpuIrhG1nixQ/edit?tab=t.0)

```[tasklist]
### Tasks
- [x] Design and build Article post template
- [x] Design and build post tag archive template
- [x] Design and build Articles & Resources archive template
- [x] Design article card element for pages
- [x] Document how to make articles and how to add the card to a page
```

**Comment by CourtneyLee333** [comment]
@DerekCaelin Ready for your review. FYI I did some editing to the [website doc](https://docs.google.com/document/d/1ilmHSeIl6wX1ORZQX_ZsrAi56IzpYCxnpuIrhG1nixQ/edit?tab=t.0) to clarify and flesh the Help Documentation content out a bit. Could use more love, but it's getting there.

**Comment by DerekCaelin** [comment]
As we discussed in the comms meeting I think these all look great. I read the guide about the "Related Readings" section, am I right that the related articles are manually populated?
