### ISSUE TITLE
Help section updates for "exposing" help seection

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#1113]
```[tasklist]
### Tasks
- [ ] Align tiles with menu - Courtney
- [ ] Add change log to "General" - Derek
- [ ] Embed [general inquiries](https://share.hsforms.com/1ed_NaMG5QGeqAguf5IlKLw5g5j2) form in a page - Derek
   - [ ] Update footer link 
- [ ] Add help section to main menu
- [ ] expose main menu - Courtney
```

**Comment by DerekCaelin** [comment]
Looks great, thank you for this.
