### ISSUE TITLE
Think through save/done button behavior throughout the app

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#1188]
Ruxandra is currently working on button component implementation. We need to look through Save and Done buttons (maybe others?) throughout the app to determine if changes need to be made in order to create consistency. 

Figma [Button behaviors page](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=11243-30581&t=3cvaU3ImHtEVrNmg-1)
```[tasklist]
### Tasks
- [x] Decide on patterns
- [x] Add patterns to component documentation
- [x] Go through individual screen designs and bring them into compliance
- [x] Add updated designs to the Button Behavior page with relevant notes
- [x] Make a github issue for each update
```

**Comment by DerekCaelin** [comment]
I added some comments to figma.

**Comment by CourtneyLee333** [comment]
Blocked because Github has reached max number of issues so I can't add more.
