### ISSUE TITLE
Expand "set map location" to take more space on a screen

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#126]
We've noticed that people with laptops in the KLC were losing a lot of their map selection screen to the Terraso header. Should the map selection screen expand to the whole window? It may be because laptops were lower resolution. 

30-40% of the window is lost to nonfunctional space.
<img width="1397" alt="image" src="https://github.com/techmatters/terraso-product/assets/10799815/7d917667-f079-4c7b-ab77-325a065d512f">

## Steps To Reproduce
1. Draft a story map
2. Click on "set map location"
3. see issue

## Design
**Set Map location view Mockup**: https://www.figma.com/file/JZawQhKeVtEEt7V3o43D4f/UX-WIP_-Story-map-V-1.1-%26-LATER?type=design&node-id=1049-8323&mode=design&t=yufQEAqCnKsoYfCa-0

**Full screen experience:**
(updated 7/5/23)
<img width="723" alt="image" src="https://github.com/techmatters/terraso-product/assets/92342777/1dfdabec-f914-4b53-8d4b-fade78daf73e">

**UI Copy (Final)**
https://docs.google.com/document/d/16LicTA5xrvK3rGmegEdlh5Myf_iG3nToo5Y0fkrCmgc/edit

Alt image text 
https://docs.google.com/document/d/1g0A25TW4SAd3Fp9x-MJ8bdKt5XVUIYDqIdMfeT0ICpg/edit

**Visual assets:**
Folder: https://drive.google.com/drive/folders/13vMaFEWqCan78SbMZxhRX7qpktoxYAa-

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/200
- [ ] https://github.com/techmatters/terraso-product/issues/232
- [ ] https://github.com/techmatters/terraso-product/issues/231
```
