### ISSUE TITLE
Slope data input

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#158]
Gather slope information for a site

## References
[Slope](https://docs.google.com/document/d/1wIZ1qJGlnPD0hsfXrV3MDAFLHav5PYkaSdnX0Ubq5DI/edit#)[
Test Cases](https://docs.google.com/spreadsheets/d/1gpVzhSpirr9toW7jMADIj2pQqJnrqdSbKE1YgmLNEg8/edit#gid=2004954072)

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=5800-13582&t=MtLyxubSlWSq1BJU-0)

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/207
- [ ] https://github.com/techmatters/terraso-product/issues/494#issuecomment-1863499557
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/249
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/127
- [ ] https://github.com/techmatters/terraso-client-shared/issues/10
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/766
- [ ] https://github.com/techmatters/terraso-backend/issues/623
- [ ] https://github.com/techmatters/terraso-product/issues/823
- [ ] https://github.com/techmatters/terraso-product/issues/824
```

## Acceptance criteria

- I can provide slope data for sites I have contributor/manager access to
- I can view data provided by others on sites I have permissions to view
- I can delete slope data for a given site and start over
- As an authenticated user, any data I contribute for slope should be tracked in the site audit log.
- Analytics should be collected according to the spec document

```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/843
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/853
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/822
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1390
```

## User Story

- As a site contributor or manager, I can provide slope and slope shape data in the US and international LandPKS apps.
- I can manually select the slope range and slope classes I want to use (see spec link), type the slope percentage in (integer value of at least 0%, or degrees between 0 and 90 degrees) or use my device's clinometer/accelerometer to measure the site's slope percentage. See [Slope spec](https://docs.google.com/document/d/1wIZ1qJGlnPD0hsfXrV3MDAFLHav5PYkaSdnX0Ubq5DI/edit#) for specific ranges
- I can manually select slope shape across two axes (down-slope and cross-slope) from three different choices:
  - concave
  - convex
  - linear

**Comment by CourtneyLee333** [comment]
@ltseng I'm wondering about the concept of deleting slope data and starting over, and general methods around editing collected data. Do we need a way for the user to "unlock" previously collected data in order to delete or change it? In other words, to make it clear their actions will overwrite what's already been collected? In the current app it would be quite easy to tap the previously chosen image without realizing it will delete the data. 

Do we want an unlock feature on all the data input sections, and a save button? I'm thinking in terms of a linear workflow, and for some user satisfaction in doing all this hard physical work, a sense of starting and completing a task might be a nice thing.

**Comment by ltseng** [comment]
I think it could be useful, as long as we put up the right guardrails. We would want to check with engineers on the feasibility of this too, since I imagine this would have database complications, and potential for data conflicts. I'm thinking this would be a useful post-MVP feature.

**Comment by CourtneyLee333** [comment]
I wonder if it would necessarily have database complications, or if it would a simpler UI thing. For example, the user might need to tap an edit button before making a change to saved data rather than just changing it. Or, if they change previously saved data they get a dialog box asking if they are sure. I think this is worth asking the BLM group.

**Comment by ltseng** [comment]
I'll add this to the list of questions for next week's meeting

**Comment by ltseng** [comment]
@shrouxm and @david-code when we get to building the digital slope meter, keep in mind that this will ideally be built as a reusable component that can be later called from the [Toolbox](#330)

**Comment by ltseng** [comment]
I've separated out the parts of this task that originally referenced landscape position and slope aspect into their own user story - [#landscape position](https://github.com/techmatters/terraso-product/issues/519)

@shrouxm is this issue ready to QA?
@david-code I'm assuming that you haven't gotten to locking down the contributor and viewer access to slope yet, right? (Just so I don't file additional unnecessary bugs)

**Comment by shrouxm** [comment]
@ltseng there are a couple bugs that became obvious once the changes were distributed so i would say hold off on QA until those are resolved!

**Comment by ltseng** [comment]
@CourtneyLee333 I have completed the functional QA of this user story and am now passing this on to you for design QA. Please note the three bugs I have found so far.

**Comment by CourtneyLee333** [comment]
@ltseng I'm so excited to see these screens! Here are a few things I found:

- I don't think auto-save is working the way it should, but I'm also not confident in the decisions we made around that until we get some user testing. We can discuss if you like, or leave it for now. I think most important for launch will be consistency of manual save vs. auto-save throughout data inputs. 
- The modal for "enter steepness percentage or degree" should show error text when user enters a degree number outside the range. I think turning the helper text red would suffice. 
![Screenshot_20240208-155233](https://github.com/techmatters/terraso-product/assets/8915145/ab0eed45-181d-44b1-a2b7-0807e17a53e4)
- And, in the spec it says there is no maximum percentage value, but an error is returned on the degree field if the percentage number sends it over its 0-89 range. How can we clarify this verbiage so that users understand what the requirement is? I don't understand it! Or maybe something needs to change in the app code so that no matter how high the percentage goes, the max for degree is 89? 
![Screenshot_20240208-155314](https://github.com/techmatters/terraso-product/assets/8915145/c88fcb52-6e8b-4c57-b62e-b47463943ba2)
- I'm concerned that the grey font is too light in the field placeholders, so I'm hoping that gets updated when they update the form styles in general. 
- As a viewer I can see the enabled done button on the screens. I know we had an asyinc discussion about this at some point. Seeing it in action, I think we should simply hide the done button from the viewer. On the steepness screen, manual and slope meter buttons should also be hidden. 
- There's a wee lag on selecting slope images. It seems slightly more pronounced on slope shape than steepness.

**Comment by ltseng** [comment]
@CourtneyLee333 I filed https://github.com/techmatters/terraso-mobile-client/issues/848 to track the styling issues separately. Regarding your last bullet point, I actually asked Garo about that directly, since I had noticed the same thing. They said:

> The image selectors aren't slow because of app performance issues but because it's actually saving the updated value to the backend before displaying it on the screen, we haven't implemented the behavior where it updates locally immediately while waiting for the backend response yet, but we'll only need to do that once and then it'll work everywhere!

**Comment by CourtneyLee333** [comment]
@ltseng I found one more design bug. On my iPad the dialog either omits the word "or" or it's covered by the close icon. The dialog title should be "Enter steepness percentage or degree".

![Image](https://github.com/techmatters/terraso-product/assets/8915145/28b0b3e2-8d79-4a5d-be34-c2109e7ec635)

**Comment by ltseng** [comment]
Thanks for catching that! Adding to https://github.com/techmatters/terraso-mobile-client/issues/848
