### ISSUE TITLE
Input soil texture/rock fragments data

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#159]
## User Story

- As a site contributor or manager, I can contribute soil texture and rock fragment data at various depths, whether standard intervals or custom intervals in the US and international LandPKS apps.
- I can select soil texture from a dropdown list or go through a guided experience to help me determine soil texture.
- I can select rock fragment volume from a set of 5 options.  See [spec](https://docs.google.com/document/d/1lE9j9gMjbwrd1z4lonxJE7lNhfc5qObEyp8yE_p_mZQ/edit#) for more specifics.

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/208
- [ ] https://github.com/techmatters/terraso-product/issues/209
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/128
- [ ] https://github.com/techmatters/terraso-client-shared/issues/10
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/853
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/623
```

## Acceptance criteria

- I can only contribute soil texture and rock fragments data to sites I have contributor/manager access to.
- I can view data provided by others on sites I have permission to view
- I can delete all soil texture/rock fragments that I have previously provided.
- Authenticated users who contribute data should have their actions logged in the site-level audit log.
- Analytics should be collected according to the spec document

[Soil texture/Rock fragments](https://docs.google.com/document/d/1lE9j9gMjbwrd1z4lonxJE7lNhfc5qObEyp8yE_p_mZQ/edit#)
[Test cases](https://docs.google.com/spreadsheets/d/1nN2St0IK0KLrwGUB7mpcoqV0dK0A8jIU4FyN1QStC3U/edit)

```[tasklist]
### Bugs
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/851
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/853
```

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/643
- [ ] https://github.com/techmatters/terraso-product/issues/823
- [ ] https://github.com/techmatters/terraso-product/issues/824
```

**Comment by ltseng** [comment]
@CourtneyLee333 this is not urgent, plus there is one bug that's preventing me from completing half of the functional test cases. If you're okay with that, you can feel free to start on the design QA at your convenience.

**Comment by CourtneyLee333** [comment]
Looking great!  A few things:

- There is no DONE button on the screen on the main screen.
- The images for rock frag seem blurry, and they have a transparent background so that the green shows through when you select one. At the minimum those images need a white background,  and ideally they will be crisp. I'm glad to rework the images according to what the engineers need. 
![Screenshot_20240212-092457](https://github.com/techmatters/terraso-product/assets/8915145/08572360-9bd4-499c-9602-6470553af03b)

**Comment by CourtneyLee333** [comment]
Also, @ltseng I'm unable to complete the contributor and viewer reviews because I'm having issues with my different accounts. I'm seeing the same sites on both of my accounts, and the app crashed on Android when I scrolled to the bottom of the Sites List. Is that the same bug you're experiencing? Do you want more detail?

**Comment by ltseng** [comment]
I wasn't able to complete the contributor test cases because of https://github.com/techmatters/terraso-mobile-client/issues/851.

I didn't see that same bug you're describing, though - can you give me a screen recording?

**Comment by ltseng** [comment]
Created the following issues for the things you pointed out above!
- https://github.com/techmatters/terraso-mobile-client/issues/859
- https://github.com/techmatters/terraso-mobile-client/issues/860
