### ISSUE TITLE
Epic: Introduce new users to Terraso value add

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#16]
# Description

Introduce first-time users to Terraso so they understand what they can use the tool for. (landscapes/groups, tools, collaboration)

# Problem

We've learned from the 1000L MEL team and a few usability tests that the functionality of Terraso is not clear and that people don't know what they can use the tool for. 

How might we introduce newcomers to Terraso to all the things they can do?

Related: https://github.com/techmatters/terraso-product/issues/38

## Home Screen

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/59
- [ ] https://github.com/techmatters/terraso-product/issues/59
- [ ] https://github.com/techmatters/terraso-product/issues/59
```

# Release Criteria

## Product
- [ ] As a new user, I want to be introduced Terraso's functions so that I know quickly what I can use it for.
- [ ] *Analytics* As a PM, I want to know at what stage people leave the onboarding process, so we can determine whether it is providing value. 

# Design 
- [ ] Implementation matches design
- [ ] Copy Editing
- [ ] Translation
- [ ] Additional changes...

# Engineering
Automated testing for:

- [ ] Correctness
- [ ] Performance
- [ ] Security
- [ ] Accessibility

# QA
Happy Path Test
- [ ] 
- [ ] 

Unhappy Path Test
- [ ] 
- [ ]
