### ISSUE TITLE
Soil structure observation

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#162]
Gather data about soil structure. 

Soil structure refers to how individual soil particles are arranged into aggregates or clumps, as well as how the pores between those aggregates are arranged. Soil structure affects water infiltration and drainage - well-aggregated soils with good structure allow for rapid and uniform infiltration, reducing the risk of surface runoff and erosion, while poorly structured soils lead to the opposite. Well-structured soil also promotes the movement of nutrients and facilitates their uptake by plant roots.

Soil structure does not directly impact any LandPKS reports like Soil ID or LCC, but is itself a vital component of measuring soil health.

## References
Spec - [Soil Structure](https://docs.google.com/document/d/1N-umsAhGAg9HQpwaeUdUqB1DEn7wosRhoHkwNTV_tko/edit)
[Soil structure section](https://drive.google.com/file/d/1WSrA7Y6ldhBGm3NUrTF5GBeXtUwfG-zU/view?usp=drive_link) from [Field Book for Describing and Sampling Soils from the NRCS  ](https://www.nrcs.usda.gov/resources/guides-and-instructions/field-book-for-describing-and-sampling-soils)
- [ ] [Project management data requirements](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9529-25274&t=gJNhf4HwFQlhbXRv-1)
- [ ] [Soil structure info sheet](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9529-24949&t=gJNhf4HwFQlhbXRv-1)
- [ ] [Soil Structure in depth options](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9563-5008&t=gJNhf4HwFQlhbXRv-1)
- [ ] [Soil Structure input screen](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9529-24949&t=gJNhf4HwFQlhbXRv-1)

### Varda project, WRB manual
[Technical sheet](https://docs.google.com/document/d/14kJW3JaltJeCp3AJ-BT25LoKuzFAgiDZ/edit)

## Design
[Figma Post-Capri design](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=9529-24949&t=UgjTmldBsxdxu3eT-1)

<img width="300" src="https://github.com/user-attachments/assets/b08de1f6-85f0-45f8-961c-943e0b929642" />

<img width="266" src="https://github.com/user-attachments/assets/53c62b5e-ca09-46fd-a92b-0ccf52b1a6ed" />

<img width="280" src="https://github.com/user-attachments/assets/43903de3-31c2-4bce-a536-7be49181acfe" />

### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/215
- [ ] https://github.com/techmatters/terraso-client-shared/issues/10
- [ ] https://github.com/techmatters/terraso-backend/issues/623
- [ ] https://github.com/techmatters/terraso-product/issues/992
- [x] https://github.com/techmatters/terraso-product/issues/1093
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/131
- [ ] Translate to Spanish
- [ ] QA
- [ ] Documentation
- [ ] https://github.com/techmatters/terraso-product/issues/1006

## Acceptance criteria

- [ ] Add structure to soil pit
- [ ] Add info sheet
- [ ] Create structure screen with picker
- [ ] Update data model 
- [ ] Permissions
  - [ ] I can add soil structure data to sites where I am a contributor/manager
  - [ ] I can view soil structure data on sites where I am a contributor/manager/viewer
  - [ ] I can delete all soil structure data that I have previously provided. 

## User Story

- As a user, I can collect soil structure data at various depths for any site I have contributor/manager access to. Specific values can be found in the [spec document](https://docs.google.com/document/d/1N-umsAhGAg9HQpwaeUdUqB1DEn7wosRhoHkwNTV_tko/edit)

**Comment by DerekCaelin** [comment]
Carissa: estimate 3 for front end, 3 for back end

**Comment by DerekCaelin** [comment]
Requested by E. Agüero in CR.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Soil Structure is a soil health characteristic that can change over time, and is not a soil property that is linked to the soil classification. In the legacy app, soil structure is included in the soil health monitoring section which is calendar-based to track change over time. 

I'm thinking, as a minimum for now, we should include the date on the soil structure input screen. When we work on the monitoring app I imagine we will include soil structure over time as well. Since the Soil ID app is a one-time-per-site jam, and soil structure can also be quite useful in this context, including a date seems like a good idea. Thoughts?

**Comment by DerekCaelin** [comment]
[Requested](https://docs.google.com/document/d/1Og_5gm865sRPN2IhxfQMf7uTToDk1aKb14IUwGlrxBQ/edit?usp=drive_link) by pedologist working in project with Varda. 

In addition to **Type**, which we have already designed, their project requires **Grade**: `strong`, `weak`, `moderate`, and **Size:**  `Very fine`, `Fine`, `Medium`, `Coarse`, `Very coarse`. Documented in [project manual](https://docs.google.com/document/d/14kJW3JaltJeCp3AJ-BT25LoKuzFAgiDZ/edit).

**Comment by DerekCaelin** [comment]
Low complexity. Review LOE.
