### ISSUE TITLE
Design/Product Task - Define and Document Terraso product principles

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-product#177]
Mural board from the meeting and synthesis
https://app.mural.co/invitation/mural/techmatters9109/1687194033733?sender=ue3adfb39ae85b9ee50a94245&key=b647df39-c19c-4938-acb3-6fd37e3cf067

- [x] Conduct design session with the team
- [x] Review, iterate
- [x] Present final draft to the team
- [x] Incorporate into our work

```[tasklist]
### Tasks
- [x] Product principles (Final internal draft) in Mural and G-doc
```

**Comment by DerekCaelin** [comment]
This is complete - next steps are to get feedback
