### ISSUE TITLE
Syncing of data

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#230]
Allow the user to send and receive information to and from the server at various events.

## References
[Syncing of Data Spec](https://docs.google.com/document/d/1I-2D44c7hNqbb2jXtpqCLvF6buS3ibmbFyUsCnZNcrM/edit#heading=h.54w02ys7n8ko)
[Ruxandra pres](https://docs.google.com/presentation/d/1HYYcyGVv4dIwQT_57i9ThMPJh7IHZriQTqftJKGlREM/edit#slide=id.p)
[Garo Syncing Mural](https://app.mural.co/t/techmatters9109/m/techmatters9109/1725489007438/2a49531c56794e292433521d263a422be8f13c3b?fromVisitorModal=true&sender=u3faecbd439cadb255c696741)
[Garo Summary](https://tech-matters.slack.com/archives/C0376RCCXD2/p1727306002860139)

#### MVP breakdown
<img src="https://github.com/user-attachments/assets/8e6813e3-b89d-457d-9205-7df686ebde1e" width="200px">

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/990
- [ ] https://github.com/techmatters/terraso-product/issues/918
- [ ] https://github.com/techmatters/terraso-product/issues/1037
- [ ] https://github.com/techmatters/terraso-product/issues/1115
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2278
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2279
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2283
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2291
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2292
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2293
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2294
- [ ] QA
- [ ] https://github.com/techmatters/terraso-product/issues/1131
```

```[tasklist]
### Old Tasks - wont use these designs for MVP
- [ ] https://github.com/techmatters/terraso-product/issues/484
- [ ] https://github.com/techmatters/terraso-product/issues/485
- [ ] https://github.com/techmatters/terraso-product/issues/486
- [ ] https://github.com/techmatters/terraso-product/issues/487
- [ ] https://github.com/techmatters/terraso-product/issues/488
- [ ] https://github.com/techmatters/terraso-product/issues/489

```

#### Triggers
- [x] synchronize data on startup for all sites and projects I belong to (uploads and downloads new data).
- [x] push client-side updates with the cloud immediately if online
    - [ ] pull if there's an error
- [x] push and pull data when device goes from offline to online
- [x] pull periodically (engineer discretion - 5 mins while app is in foreground?)

##### Sync Behavior
- [ ] the client will send the values of the entire site in which the user has modified a field since last sync
  - [x] the server will unconditionally accept these values
  - [ ] the server will create a log entry with the values the client sent and the time that they were received (we won't immediately do anything to expose those log entries, but they'll be available via support request and could be exposed in future)
  - [x] Push changes at a field level!

**Nongoal:**
- [ ] for MVP, we will NOT need to keep track of **when** the user has input data
- [ ] We will not try to recreate a site that has been deleted
- [ ] We will not try to add data to a site that has been moved to a project where the contributor does not have permissions

**Comment by DerekCaelin** [comment]
We plan to have a sync (with updated API calls) every time the data changes: [slack conversation](https://tech-matters.slack.com/archives/C0376RCCXD2/p1724079193661639?thread_ts=1723814186.933359&cid=C0376RCCXD2)

**Comment by DerekCaelin** [comment]
Garo [notes](https://tech-matters.slack.com/archives/C0376RCCXD2/p1727306002860139): 

> we discussed several possible enhancements to this workflow, but agreed that since:
> we expect data conflicts will be edge cases anyway, and
> we can advise users to record data for a site on only one device
> we can start with the above implementation, and revisit which enhancements make sense if we start receiving reports of user frustration due to data conflicts

**Comment by DerekCaelin** [comment]
One option:
- "pull" button in the footer menu
- go to screen that describes the behavior
