### ISSUE TITLE
Design task: Spec the How-to content below the page title

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-product#232]
```[tasklist]
### Tasks
- [x] Prepare the mockup for engineer: https://www.figma.com/file/JZawQhKeVtEEt7V3o43D4f/UX-WIP_-Story-map-V-1.1-%26-LATER?type=design&node-id=1049-8323&mode=design&t=yufQEAqCnKsoYfCa-0
- [x] Draft the content: https://docs.google.com/document/d/16LicTA5xrvK3rGmegEdlh5Myf_iG3nToo5Y0fkrCmgc/edit
- [x] Review with PM & Editors
- [x] Finalize Copy
- [x] Create the visual assets: 4 images
```

**Visual assets:** 
Folder: https://drive.google.com/drive/folders/13vMaFEWqCan78SbMZxhRX7qpktoxYAa-
File names: `Howto-img1...`  -- 4 PNGs

**Comment by DerekCaelin** [comment]
No need to update figma once the copy has been revised.
