### ISSUE TITLE
Design task - show data file on story map - part 1

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#240]
**Creating a story map workflow:** FOCUS ON GEOSPATIAL DATA MANIPULATION FOR THIS TASK:
https://app.mural.co/t/techmatters9109/m/techmatters9109/1669812969041/88ff35af8df80198ce7d683bb0d6e25a04da3327?sender=ue3adfb39ae85b9ee50a94245

Product spec: https://docs.google.com/document/d/1vfRvb6DE_7NSCZi9cOhahT2uwILzLM3KOmEIe2t1I4M/edit

```[tasklist]
### Tasks
- [x] Review the previous studies on setting the location in Story maps
- [x] Sketch workflow & idea
- [x] Create wireframes
- [x] Review wireframes with PM
- [x] Iterate wireframe
```

**Comment by DerekCaelin** [comment]
Engineers might want to break this into component:
- lat/long search
- click on lat/long to center on my location
- basemap selection
- data map selection
