### ISSUE TITLE
Product task - write up process to generate 1000L user journey

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#249]
### References
- [WIP user journey](https://app.mural.co/t/techmatters9109/m/techmatters9109/1687203577079/504adc5d9e17490fd952b18a1f2f824886b2002c?sender=u3faecbd439cadb255c696741)- [Notes](https://app.mural.co/t/techmatters9109/m/techmatters9109/1689359578507/2c78123ba0e724a300cc125291847920a1e3c83c?wid=0-1689359915397)

```[tasklist]
### Tasks
- [x] Write up task, assign size, get back to Hana
- [x] ASsign tasks to 1000L DT members
- [ ] https://github.com/techmatters/terraso-product/issues/264
- [ ] improve
```
