### ISSUE TITLE
Tracking audit logs for projects and sites

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#25]
## User Story

- As a user with permission to edit a site or project, any changes I make to the site or project should be tracked in the site and project audit logs.

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-product/issues/149
- [ ] https://github.com/techmatters/terraso-product/issues/150
```
```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/774
- [ ] https://github.com/techmatters/terraso-backend/issues/356
- [ ] https://github.com/techmatters/terraso-backend/issues/336
- [ ] https://github.com/techmatters/terraso-backend/issues/553
- [ ] https://github.com/techmatters/terraso-backend/issues/552
- [ ] https://github.com/techmatters/terraso-backend/issues/551
- [ ] https://github.com/techmatters/terraso-backend/issues/763
- [ ] https://github.com/techmatters/terraso-backend/issues/701
- [ ] https://github.com/techmatters/terraso-backend/issues/773
- [ ] https://github.com/techmatters/terraso-backend/issues/771
- [ ] https://github.com/techmatters/terraso-backend/issues/772
- [ ] https://github.com/techmatters/terraso-backend/issues/915
- [ ] https://github.com/techmatters/terraso-backend/issues/916
```

## Acceptance criteria

- Whenever changes are made to a site or project, the date, time, actor, resource/context, and metadata of the corresponding event should be documented in the relevant audit log.
- When I log data for a site, the timestamp that is logged for that data entry should correspond to when I saved my changes in the app, not when my device synced data to the cloud

[Audit log spec](https://docs.google.com/document/d/1OezErhcF0FshY3nSI_xf35svdRATQkNV8RWgogsKU8A/edit#)

**Comment by DerekCaelin** [comment]
We will revisit the concept of an audit log. It may still be needed for federal projects. For now, the feature is not planned.
