### ISSUE TITLE
Design Task - LandPKS Logo, Colors - collaborate w Leesa comm.

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#273]
**SCOPE UPDATE (8/21/23):** 
Collaborate with Lesa comm as they will work on the LPKS logo refresh, App store icons, etc. 

**LPKS brand refresh Mural board:** 
https://app.mural.co/t/techmatters9109/m/techmatters9109/1691704383958/f8252aba9efa6c28cf8994bde0502a5c15c72eba?sender=ue3adfb39ae85b9ee50a94245

```[tasklist]
### Tasks
- [x] LPKS brand exercise
- [x] Provide the existing Terraso style guides to Lesa communications
- [ ] https://github.com/techmatters/terraso-product/issues/387
```

**Comment by DerekCaelin** [comment]
Hana points out that there is some uncertainty here:  If we limit the scope to polishing the current logo, it will be reduced.

**Comment by DerekCaelin** [comment]
Could be 3-5 points if the scope is reduced.
