### ISSUE TITLE
Bosques y Tecnología - support documents and presentation

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#281]
## Description
Amaya and Hana to work on materials for presenting and testing with co-design partners in Mexico.

Workshop planning doc: https://docs.google.com/document/d/14Yvp72j7K5fd6Q82nKVvuGWsvdkYHdfDof_Gyr31f2E/edit

```[tasklist]
### Tasks
- [x] Plan the slide deck
- [x] Draft the attendee assigment email forward to organizer
- [x] Construct the slide deck
- [x] Review the slide deck
```
