### ISSUE TITLE
E2E Testing - August

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#282]
Timeboxed task for developing an E2E test and implementing it

```[tasklist]
### Tasks
- [ ] Product Task - e2e - create spreadsheet of testing experiences
- [ ] Product Task - e2e - write test for a process
- [ ] Engineering Task - e2e - implement test (time boxed) 
```
