### ISSUE TITLE
Terraso Story Maps Work on Mobile devices

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#299]
```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/142
- [ ] https://github.com/techmatters/terraso-product/issues/132
- [ ] Build story maps while offline
- [ ] in story maps, set chapter location with device GPS
- [ ] in story maps, capture images from phone camera
- [ ] in story maps, capture video from phone camera
```
