### ISSUE TITLE
Selecting a site/temporary location on the map

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#316]
Select a point on a map as the first step in possibly creating a location. Selec Provide users with the most likely soil to be present. 

## References
[Home Screen](https://docs.google.com/document/d/1weFSC4n4-yBXy2ejRoyXJBVbFYfujZD4oa9jSwkx73U/edit#)

Final work is dependent on https://github.com/techmatters/terraso-backend/issues/1251

## Design
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-13278&mode=design&t=3XXCUsJRxLmrQY78-0)

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/318
- [ ] https://github.com/techmatters/terraso-product/issues/319
- [ ] https://github.com/techmatters/terraso-product/issues/321
- [x] https://github.com/techmatters/terraso-mobile-client/issues/155
- [ ] https://github.com/techmatters/terraso-product/issues/647
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1207
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1341
- [ ] https://github.com/techmatters/terraso-product/issues/648
```

```[tasklist]
### Issues to resolve
- [ ] https://github.com/techmatters/terraso-product/issues/774
```

### Select temporary Location
- [ ] As a user, when I select a location on the map that hasn’t been converted to a site yet, I see a popover that contains:
  - [x] Latitude and longitude
  - [ ] Top soil ID match (US)
  - [x] Elevation
  - [x] A button to "Create Site" that initiates the Site creation process
  - [x] A button to "Learn More" that initiates the U.S. Location Dashboard experience: https://github.com/techmatters/terraso-product/issues/667

### Site context
- [x] As a user, when I select a site from the map, I want to see a popover that contains:
  - [x] Site name (selecting site name should load of the site dashboard: https://github.com/techmatters/terraso-product/issues/667
  - [x] Project name
  - [x] Thumbnail of satellite image
  - [x] Number of site members (or project members)

**Comment by DerekCaelin** [comment]
Moved this issue back to "in progress" because it is not ready for final QA (issue is dependent on implementation of SoilID algorithm).
