### ISSUE TITLE
Kobo Support - Translate the account creation UI

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#320]
Pilar identified the translation problem in the account creation process of KoBo.

```[tasklist]
### Tasks
- [x] Get a list of strings to be translated for KoBo
- [x] Have the strings translated
- [x] Send strings to Kobo
```

**Comment by DerekCaelin** [comment]
https://docs.google.com/spreadsheets/d/1P_H85YLktxYFTnoftOu4F9_jVtQn88LY45tSmJnO-pw/edit#gid=0

**Comment by DerekCaelin** [comment]
Kobo team had follow up request.
