### ISSUE TITLE
Design Task - research solutions to story maps concurrency problem

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#345]
See parent user story. Objective is to explore and consider, but not rigorously design, different methods for addressing concurrency problem. Share your recommendation on approach from a design perspective.
```[tasklist]
### Tasks
- [x] Understand the collaboration scenarios from users
- [x] Explore ways to handle the concurrency problems
- [x] Documnet the recommendation for short-term and long-term
```

Document (Mural)
https://app.mural.co/t/techmatters9109/m/techmatters9109/1695335284992/35da44e1ff74884d525f2e1689598d8a3b71655c?sender=ue3adfb39ae85b9ee50a94245

**Comment by DerekCaelin** [comment]
We've learned that users expect relay based editing.
