### ISSUE TITLE
Finalize login UI

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#356]
We put in a quick login page for the usability study, but the final login page depends on the sign in options, logo, taglines, etc.

Need to add both Sign in with Apple and Sign in with Microsoft
```[tasklist]
### Tasks
- [x] create the Login screen mockup
- [x] Get feedback from the team
- [x] Iterate per feedback
- [x] Final design approved
```

[LandPKS MUI Library](https://www.figma.com/file/7ZD5nE1IZKRHUIhrLkekoz/LandPKS-MUI-for-Figma-v5.11.1---Material-UI?node-id=8375%3A86793&t=e12gnjGPvVsDDbF9-1)

:art: [Login screen mockup](https://www.figma.com/file/5nUT64WqA1i68J9TtmeqBv/LPKS-Login-screen-for-UT?type=design&node-id=50-117&mode=dev)

## Additional context
Sign-in branding guidelines:
- Google: https://developers.google.com/identity/branding-guidelines
- MS: https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-add-branding-in-apps
- Apple: https://appleid.apple.com/signinwithapple/button

**Comment by CourtneyLee333** [comment]
@Hanal-code do you want to take this ticket?

**Comment by ltseng** [comment]
I have moved this issue to a new user story, which itself is scheduled for completion in November, meaning that I'd like to have the design work started this month. Will that be possible @Hanal-code?

**Comment by Hanal-code** [comment]
@ltseng  yes, I can work on this first. However, I am not clear the scope. Who will write the user stories? Who can I work with to discuss the screen flow - you or Derek?

**Comment by ltseng** [comment]
I don't have a formal spec set out for this, but the parent issue should provide a quick starting point. I am ignoring anonymous usage of the app for MVP as well. Please work with me and send me any questions you might have!

**Comment by Hanal-code** [comment]
@ltseng @CourtneyLee333 Can you review the LPKS login screen with two button/label options
https://www.figma.com/file/5nUT64WqA1i68J9TtmeqBv/LPKS-Login-screen-for-UT?type=design&node-id=50%3A117&mode=design&t=W0lDhHbNJxYKKKD2-1

**Comment by ltseng** [comment]
Left a comment

**Comment by CourtneyLee333** [comment]
So did I.

**Comment by Hanal-code** [comment]
Mockup deliverable: https://www.figma.com/file/5nUT64WqA1i68J9TtmeqBv/LPKS-Login-screen-for-UT?type=design&node-id=50%3A117&mode=dev

**Comment by ltseng** [comment]
Looks perfect!
