### ISSUE TITLE
LandPKS Public Data Portal

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#373]
Download public data from LandPKS Soil ID.

### User stories
- [ ] https://github.com/techmatters/terraso-product/issues/466
- [ ] https://github.com/techmatters/terraso-product/issues/467
- [ ] https://github.com/techmatters/terraso-product/issues/468
- [x] https://github.com/techmatters/terraso-product/issues/469

### Design
- [ ] https://github.com/techmatters/terraso-product/issues/374
- [ ] https://github.com/techmatters/terraso-product/issues/402

## References
[Product Spec - Data Portal](https://docs.google.com/document/d/152G_1AgYd2zt3yCl3TezbgFn4WHV1Br92SBnFVQWPHE/edit#heading=h.54w02ys7n8ko)

**Comment by Hanal-code** [comment]
Land PKS web experience feature list ([G-sheet)](https://docs.google.com/spreadsheets/d/1YuH57WkkcLQi2TCxYQZ0R-188z0KfkIz96YHFdfRCcg/edit#gid=0)

**Comment by DerekCaelin** [comment]
[Request from V.C. to download his project's data.](https://app.hubspot.com/contacts/9151742/ticket/25385491554/?engagement=81946521622)
M.M from ISDA requested legacy data download.
