### ISSUE TITLE
Design task - design experience for LandPKS Data Portal

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#402]
See parent task for more details. Goal is MVP from [the product spec.](https://docs.google.com/document/d/152G_1AgYd2zt3yCl3TezbgFn4WHV1Br92SBnFVQWPHE/edit#heading=h.zb56brifkjr) 
```[tasklist]
### Tasks
- [x] Knowledge sharing: LPKS app UI for site dashboard/reports
- [ ] https://github.com/techmatters/terraso-product/issues/459
- [x] Legacy LPKS Analytics data - Google Analytics
- [x] Create wireframes
- [x] Review wireframes with team
- [x] Iterate wireframes
- [x] Visual design
- [x] UI text refinement
- [x] Final review with PM
```

**Comment by Hanal-code** [comment]
@ltseng Can you move this task done as you approved the design this morning?

**Comment by ltseng** [comment]
Yep!
