### ISSUE TITLE
Design Toolbox for existing tools

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#442]
```[tasklist]
### Tasks
- [x] Soil texture guide
- [x] Soil color guide
- [x] Slope Meter
- [x] AWC and Infiltration calculator
- [x] Basic location, layout, and styles for Toolbox
```

[Toolbox wireframes](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=3993%3A31778&mode=design&t=AiJ6mks96Ays9ZIw-1)

**Comment by ltseng** [comment]
Toolbox minus AWC looks good. Just hand one question about the inclusion of WOCAT. Otherwise approved!

**Comment by Hanal-code** [comment]
@CourtneyLee333 I left a minor comment for text in Figma.

**Comment by CourtneyLee333** [comment]
Ready for review at BLM meeting.
