### ISSUE TITLE
Landscape Investment Portfolio

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#45]
# Description
Build a mapping tool that allows users to answer specific questions about landscape projects, so they produce an explorable map of landscape activities that need funding. 

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/385
- [ ] Product Task - Write Spec for Landscape Investment Portfolio
```

# Problem
LPs lack a way to visually present current, planned, and prospective projects to stakeholders interested in _______ topic.

# References
* [Product Spec](https://docs.google.com/document/d/1vq_7-dMT-k6iP9sA05HbYkbvgRspvaKqGggY8qgLiGQ/edit#)
* [Spreadsheet form](https://docs.google.com/spreadsheets/d/12-lv00y8HE3yjsJ9etIcTiXDmVIpQ4Ef5EEDe4mbPqU/edit#gid=749084247)
* [One Earth Navigator](https://www.oneearth.org/navigator/)

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/10799815/231775229-dcc7ee36-4750-4c8c-a0eb-8ff18510ac7a.png">

```[tasklist]
### Pre-requisites
- [ ] https://github.com/techmatters/terraso-product/issues/42
- [ ] https://github.com/techmatters/terraso-product/issues/20
- [ ] https://github.com/techmatters/terraso-product/issues/58
```

# Release Criteria

## Product
- [ ] As a user, I want to able to start a landscape investment portfolio and signify whether I want to share it with a landscape or a group, so I can collaborate with others
- [ ] As a user, I want to answer [a preset list of questions about projects](https://docs.google.com/spreadsheets/d/12-lv00y8HE3yjsJ9etIcTiXDmVIpQ4Ef5EEDe4mbPqU/edit#gid=749084247) while drawing projects within the landscape.
- [ ] I want to be able to save a draft so I can come back over multiple sessions
- [ ] I want to be able to share my draft work with individuals 
- [ ] I want to be able to share the published landscape investment portfolio with groups and landscapes, so it can be discovered by others. 

## Design 
- [ ] Implementation matches design
- [ ] Copy Editing
- [ ] Translation (Spanish)
- [ ] Additional changes...

## QA
Happy Path Test
- [ ] 
- [ ] 

Unhappy Path Test
- [ ] 
- [ ]
