### ISSUE TITLE
UX writing audit

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#455]
UX writing audit using https://hemingwayapp.com/ and https://theuxcookbook.com/writing-for-the-web 
Get rid of “Learn More” buttons and links, make more specific

```[tasklist]
### Tasks
- [x] Site Soil ID first draft
- [ ] Site Soil ID Laura's review and help/info content creation
- [ ] Site Soil ID final draft
- [x] Data Inputs first draft
- [ ] Data Inputs Laura's review and help/info content creation
- [ ] Data Inputs final draft
- [x] Home Screen first draft
- [x] Home Screen final draft
- [x] Project Management first draft
- [x] Project Management final draft
- [x] Site Creation first draft
- [x] Site Creation final draft
- [x] Managing a Site first draft
- [x] Managing a Site final draft
- [x] Location Dashboard first draft
- [ ] Location Dashboard Laura's review
- [ ] Location Dashboard final draft
- [x] Site AWC first draft
- [ ] Site AWC Laura's review and help/info content creation
- [ ] Site AWC final draft
- [x] Climate Report first draft
- [ ] Climate Report Laura's help/info content creation
- [ ] Climate Report final draft
- [x] Toolbox first draft
- [ ] Toolbox Laura's review and help/info content creation
- [ ] Toolbox final draft
```

**Comment by CourtneyLee333** [comment]
Home Screen final draft has slight edit to https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=2547%3A10394&mode=design&t=N35CW0JFTYIyB9iV-1

**Comment by CourtneyLee333** [comment]
I also pinged Laura in the Data Inputs doc but haven't heard a response yet.

**Comment by ltseng** [comment]
I pinged Laura again in the Data inputs doc today, and will check with Steve on whether they met. 

Am I tagged everywhere in the Figma that needs final verbiage?

**Comment by CourtneyLee333** [comment]
@ltseng Every task in the list that mentions Laura's name is ready for their review/creation. Can we go ahead and send all of this so they understand the magnitude of work? Should you and I circle up first to get clear on what's needed? Or, is there detail you'd like me to provide in an asynchronous way?

**Comment by ltseng** [comment]
Can you and I meet first to figure out what, if anything, is still awaiting my review before asking Laura? I've lost track of it all...

**Comment by CourtneyLee333** [comment]
Sure! Nothing is awaiting your review, but let's talk and get a plan together, make sure we're on the same page.

**Comment by ltseng** [comment]
I could have sworn I had things to look at from your comment in this issue last week, but if not, that's good! Still would love to meet though. Thanks for setting up that meeting!

**Comment by CourtneyLee333** [comment]
@ltseng I've added Toolbox items to the list.

**Comment by ltseng** [comment]
Thanks for the heads up, I'll make another document for that

**Comment by CourtneyLee333** [comment]
@ltseng Is it possible to move this subissue out of the UX Debt parent issue? Or we could re-create the list elsewhere? That way, I can close the UX Debt issue.

**Comment by CourtneyLee333** [comment]
Closing this issue as we have another user story that overlaps this one #285
