### ISSUE TITLE
Design Task - Review Editorial Style Guide with end user

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#458]
## Description
Our continuing efforts to improve the [Terraso Editorial Style Guide.](https://docs.google.com/document/d/1txlmcir4Ri4CK-DlGOujN7k5PN4cwi5z5SI_P09sh2s/edit#heading=h.p1iv02v28fxd)

- [ ] Get feedback from content creators. Usefulness, missing content. What do you need?

related doc: https://docs.google.com/document/d/1zYIfmnZSlksfbZyFE_zE61dcAo-GxTyVu3CoRevcqoU/edit#heading=h.hps5kfug9pgp

```[tasklist]
### Tasks
- [x] Contraction decision
- [x] Oxford comma and AP style decision
- [x] Review meeting with LPKS external content creators
```

**Comment by Hanal-code** [comment]
- The editorial style guide was updated for the external editors/viewers on 12/11.
- Terraso pattern-related style guides were moved to `[WORK IN PROGRESS] Terraso 1000L style guide`
