### ISSUE TITLE
Integrate with 3rd party data collection tools for collaboration.

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#46]
# Description

Allow Terraso users with a Kobo account to collaborate with their partners in groups and landscapes, to see their Kobo data in Terraso, and to make maps out of it. 

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/87
- [ ] https://github.com/techmatters/terraso-web-client/issues/994
- [ ] Build maps from Kobo-collected data
- [ ] https://github.com/techmatters/terraso-product/issues/56
```

# References

- [Product Spec - Share Living Kobo Datasets](https://docs.google.com/document/d/1Tqch8Z_gYLLa3or238Lhrl5kXq1jfgC7tZblF6_TuX0/edit#heading=h.54w02ys7n8ko)
- 

# Release Criteria

## Product
- [ ] User Story
- [ ] User Story
- [ ] User Story

## Design 
- [ ] Implementation matches design
- [ ] Copy Editing
- [ ] Translation (Spanish)
- [ ] Additional changes...

## QA
Happy Path Test
- [ ] 
- [ ] 

Unhappy Path Test
- [ ] 
- [ ]
