### ISSUE TITLE
Brand guideline for LandPKS

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#491]
Develop a document that describes what kind of usage of the logo and other branding collateral is recommended for LandPKS, including, but not limited to:

- When to use the wordmark
- When to use a border around the LandPKS logo
- What the relative sizes/spacing between the logo and icon should be
- When to use the "knockout" version of the app
- etc
```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/493
- [x] Draft the Brand guideline outline
- [x] Add content
- [x] Review the brand guideline with team
```
**DESIGN:** 
Figma file: https://www.figma.com/file/ty8g0laY7qmA4N2olX1mpy/LPKS-Brand-guidelines?type=design&node-id=13%3A4086&mode=design&t=mz6fyu7q8dRgHu0W-1

**Comment by Hanal-code** [comment]
LPKS brand guidelines draft: https://docs.google.com/document/d/1t3PGSv3x3O-V3NYXBV6hptG3erZ95aPX3yCp29Ogf74/edit#heading=h.70r68nydjml8

**Comment by ltseng** [comment]
Is this ready for me to review/edit?

**Comment by Hanal-code** [comment]
@ltseng Not yet. I am planning to work on it later this week and next week and will let you know to review it.

**Comment by ltseng** [comment]
Sounds good!

**Comment by Hanal-code** [comment]
The final version is uploaded to G-drive: https://drive.google.com/drive/folders/1huETBZh_1QGOuH17daN5bJuJX2akGTri
