### ISSUE TITLE
Design task - show data file on story map - part 2

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#495]
```[tasklist]
### Tasks
- [x] Experiment with lightbox alternate option
- [ ] https://github.com/techmatters/terraso-web-client/issues/1198
- [x] present to engineering
- [x] iterate on feedback
```

DESIGN MOCKUP (WORK-IN-PROGRESS):
Latest iteration per engr feedback(1/29/24): https://www.figma.com/file/uZKZcmVaM7bhDFnQLhgyCI/Add-map-to-Story-Map?type=design&node-id=118-994&mode=design

**Comment by Hanal-code** [comment]
Feedback: Map names in Terraso.
1) What are they? 
- Boundary map (a.k.a. Landscape polygon/map)
- Data map
- Feature map (a.k.a.  Project map)
- Story map

2) Easy to recall and differentiate? 
A: don't know if they are clear enough in user's head. NEXT: How can we find that out? 

Maps in Terraso: https://docs.google.com/document/d/1Dkh-DvQaAkAkBUlw09KxkJJVHzpDrTjLiRQRwEiisfY/edit#heading=h.ufh2ybpikzb3

**Comment by Hanal-code** [comment]
@DerekCaelin Presenting to Risaralda is a separate task from the ad-hoc study according to the list above. Is it an outdated list?
