### ISSUE TITLE
Hamburger menu navigation items

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#504]
## Description

Out of Capri launch.

- As a user, I can use the hamburger menu to access functions for:
  - User settings - option to see which account I'm logged in as, set units between English and Metric, and delete account (#418)
  - Help documentation
  - Log out

```[tasklist]
### Design
- [ ] https://github.com/techmatters/terraso-product/issues/505
- [ ] https://github.com/techmatters/terraso-product/issues/506
- [ ] https://github.com/techmatters/terraso-product/issues/507
- [ ] https://github.com/techmatters/terraso-product/issues/564#issuecomment-1969252690
```

```[tasklist]
### Front end
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/743
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/803
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/804
```

```[tasklist]
### Back end
- [ ] https://github.com/techmatters/terraso-backend/issues/1111
- [ ] https://github.com/techmatters/terraso-backend/issues/1112
```

## Acceptance criteria

- As a user, I can use the hamburger menu to:
  - Access help text 
  - Change my user settings
  - Log out of my account 

## vLater

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by DerekCaelin** [comment]
Although we probably will pick up the hamburger again, I'm closing this issue and will start fresh
