### ISSUE TITLE
Story Maps are more collaborative, more flexible, can showcase more types of data

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#51]
# Description

Build upon story maps feature with high priority requests by users.

```[tasklist]
### Components
- [ ] https://github.com/techmatters/terraso-product/issues/20
- [ ] https://github.com/techmatters/terraso-product/issues/17
- [ ] https://github.com/techmatters/terraso-web-client/issues/786
- [ ] https://github.com/techmatters/terraso-product/issues/3
- [ ] https://github.com/techmatters/terraso-web-client/issues/773
```
