### ISSUE TITLE
(Idea) Landscape Tech Forum

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#510]
## Problem
Users need guidance on accomplishing tech tasks. 

## References
- [James suggestion](https://tech-matters.slack.com/archives/C05B4U4L413/p1704295519019639)
- [Earth Defender ](https://forum.earthdefenderstoolkit.com/) (powered

## Process
```[tasklist]
### Issues
- [ ] Product task - write spec
- [ ] Design research (if needed)
- [ ] Engineering research (if needed)
- [ ] Design task - design experience
- [ ] Team Reviews design
- [ ] Design task - Copy edits
- [ ] Engineering task - implement design
- [ ] (optional) Design tweaks based on learning
- [ ] Product tests against criteria
- [ ] Translation
- [ ] Product task - Write QA plan
- [ ] Usability testing
```

### Product
- [ ] User Story
- [ ] User Story
- [ ] User Story

### QA
Happy Path Test
- [ ] 
- [ ] 

Unhappy Path Test
- [ ] 
- [ ]
