### ISSUE TITLE
Quality of Life Enhancements

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#52]
# Description

General high-prioritiy improvements to the user experience.

```[tasklist]
### Components
- [ ] https://github.com/techmatters/terraso-web-client/issues/665
- [ ] https://github.com/techmatters/terraso-web-client/issues/811
- [ ] https://github.com/techmatters/terraso-product/issues/16
- [ ] https://github.com/techmatters/terraso-web-client/issues/631
- [ ] https://github.com/techmatters/terraso-product/issues/10
- [ ] Shared data files module doesn't show most relevant files.
```
