### ISSUE TITLE
View basemaps offline

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#53]
Offline maps are useful to help the user situate themselves within an landscape. How might we allow the user to see basemaps while offline?

## References
[Offline Maps](https://docs.mapbox.com/help/troubleshooting/mobile-offline/)

```[tasklist]
### Tasks
- [ ] Product Spec?
- [ ] https://github.com/techmatters/terraso-product/issues/1022
- [ ] Design Experience - cache maps offline
- [ ] Implement offline basemaps
- [ ] QA
```

## Acceptance Criteria
- TBD
