### ISSUE TITLE
Prototype Test - Data Maps in Story Maps

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#535]
- [x] Design [study plan protocol ](https://docs.google.com/document/d/1ktKeWKjHW2ji2fnvVCbgXyC_X7o_TjZeeItEnrO0-AQ/edit#heading=h.3d87emb7zbj7)[Hana]
- [x] Recruit people [Derek]
- [x] Prepare the sessions: protocol, prototype [Hana]
- [x] 5 interviews with design partners. 
- [x] Synthesize results: [Mural board](https://app.mural.co/t/techmatters9109/m/techmatters9109/1709048117261/182cea95fb4679ceb7cca180ed7483695d302aa4?sender=ue3adfb39ae85b9ee50a94245)

See parent issue for details.
```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/540
```

**Comment by DerekCaelin** [comment]
- Giannina
- Pilar
- Grace
- Leah

**Comment by Hanal-code** [comment]
- Ad-hoc study protocol, raw notes, etc. (G-drive): https://drive.google.com/drive/folders/1t0UMHVcZVr9se_0kVb9Kr11VoBdZSe19

- Synthesis & analysis: Mural board: https://app.mural.co/t/techmatters9109/m/techmatters9109/1709048117261/182cea95fb4679ceb7cca180ed7483695d302aa4?sender=ue3adfb39ae85b9ee50a94245
