### ISSUE TITLE
Create UX Research Strategy for 2024

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#538]
```[tasklist]
### Tasks
- [ ] Problem statements
- [ ] Define UX success metrics
- [ ] Types of research to conduct
- [ ] Timeline for research
```

[WIP LandPKS UX Research Strategy 2024](https://docs.google.com/document/d/1E3PCne11s8E-5vnKLLHcpeDOdFngTkzuYnntw3PYaMA/edit?usp=sharing)
