### ISSUE TITLE
Maps produced by uploading data files or drawing/clicking in the UX

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#54]
# Description

High priority improvements to Terraso's mapping process

```[tasklist]
### Components
- [ ] https://github.com/techmatters/terraso-web-client/issues/815
- [ ] https://github.com/techmatters/terraso-web-client/issues/778
- [ ] https://github.com/techmatters/terraso-product/issues/93
- [ ] https://github.com/techmatters/terraso-product/issues/130
```
