### ISSUE TITLE
LandPKS CRM updates

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#547]
[CRM planning document](https://docs.google.com/document/d/1yw0C1bdhfcdrxmm1HdoVJdsjKOw5cfzuEcwFoFJX7qw/edit?usp=sharing)

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/558
- [ ] https://github.com/techmatters/terraso-product/issues/559
- [ ] https://github.com/techmatters/terraso-product/issues/560
- [ ] https://github.com/techmatters/terraso-product/issues/561
- [ ] https://github.com/techmatters/terraso-product/issues/556
```

**Comment by CourtneyLee333** [comment]
On hold until decisions are made about moving and creating new content on Terraso website.

**Comment by CourtneyLee333** [comment]
@ltseng Here is the issue for the Hubspot work that we spoke of this morning. The tasks in the list are the ones that need to be assigned to Paul. There is detail in the referenced G-doc, and I can add more to the subissues if needed. In the G-doc I yellow highlighted the ones related to "LandPKS Users" list as that part still has a lot of uncertainty.

**Comment by paulschreiber** [comment]
I've made a list in HubSpot, imported the existing users and updated the form.

**Comment by CourtneyLee333** [comment]
@paulschreiber 

- Why did you choose a static list for subscribers rather than active?
- When I tried to subscribe via the form in the footer on landpotential.org it didn't work. I entered name and email address, but upon clicking "Get updates" the button stat changed but I got no success message and my contact record was not added to Hubspot. This leads me to believe anyone trying to sign up right now is unsuccessful as well.

**Comment by paulschreiber** [comment]
• Active means that it's dynamically created based on HubSpot criteria. Static means we manage the membership.
• I will debug the subscription failure.

**Comment by CourtneyLee333** [comment]
So is there an automation set up that when someone subscribes to the LandPKS newsletter they get put into that static list? I don't see any automations in Hubspot. And I don't see the LandPKS newsletter sign-up form either. I might need you to explain to me how you've set things up.

**Comment by CourtneyLee333** [comment]
Also, (this might be a task for elsewhere) we should rename the existing forms in Hubspot to include "Terraso" or some way to delineate general Terraso forms from LandPKS forms.

**Comment by CourtneyLee333** [comment]
How will people unsubscribe from the list?

**Comment by paulschreiber** [comment]
>When I tried to subscribe via the form in the footer on landpotential.org it didn't work. I entered name and email address, but upon clicking "Get updates" the button stat changed but I got no success message and my contact record was not added to Hubspot. This leads me to believe anyone trying to sign up right now is unsuccessful as well.

The subscription form is now working for users not logged in to WordPress.

>How will people unsubscribe from the list?

Emails will have an unsubscribe link in the footer.

**Comment by CourtneyLee333** [comment]
Great, I tested and it works.

**Comment by DerekCaelin** [comment]
I've added `Terraso` to lists I recognize.
