### ISSUE TITLE
Write blog post

### ISSUE THREAD

**Issue by hamriclr** [techmatters/terraso-product#548]
[Google Doc draft](https://docs.google.com/document/d/120tPPl21MR5peuVbNGXALt4GjYx3w5zyB9u2bpvqtCg/edit)

```[tasklist]
### Tasks
- [x] Draft blog post
- [x] Review blog post
- [ ] Publish to website blog
- [ ] Create as newsletter draft
- [ ] Send out newsletter
```
