### ISSUE TITLE
LandPKS Foundational Documentation 

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#550]
Design the web-based documentation experience, and write critical articles for users getting started with LandPKS.

[Outline of material](https://docs.google.com/document/d/1Fvy5cBpCMq-EOt2Ll7OMZq5S-y_qxO3ayzZrz86Aa00/edit#heading=h.x2hcacbes0ko)

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/819
- [ ] https://github.com/techmatters/terraso-product/issues/820
- [ ] https://github.com/techmatters/terraso-product/issues/821
- [ ] https://github.com/techmatters/terraso-product/issues/822
- [x] Implement web documentation section on staging
- [x] migrate web documentation to production
```

```[tasklist]
### How to
- [ ] https://github.com/techmatters/terraso-product/issues/927
- [ ] https://github.com/techmatters/terraso-product/issues/928
- [ ] https://github.com/techmatters/terraso-product/issues/930
- [ ] https://github.com/techmatters/terraso-product/issues/945
- [ ] https://github.com/techmatters/terraso-product/issues/931
- [ ] https://github.com/techmatters/terraso-product/issues/932
- [ ] https://github.com/techmatters/terraso-product/issues/933
- [ ] https://github.com/techmatters/terraso-product/issues/934
- [ ] https://github.com/techmatters/terraso-product/issues/935
- [ ] https://github.com/techmatters/terraso-product/issues/937
- [ ] https://github.com/techmatters/terraso-product/issues/936
- [ ] https://github.com/techmatters/terraso-product/issues/939
- [ ] https://github.com/techmatters/terraso-product/issues/929
- [ ] https://github.com/techmatters/terraso-product/issues/940
- [ ] https://github.com/techmatters/terraso-product/issues/941
- [ ] https://github.com/techmatters/terraso-product/issues/942
- [ ] https://github.com/techmatters/terraso-product/issues/943
- [ ] https://github.com/techmatters/terraso-product/issues/1066
- [ ] https://github.com/techmatters/terraso-product/issues/1067
```

```[tasklist]
### Write Science Documentation
- [ ] https://github.com/techmatters/terraso-product/issues/624
- [ ] What is LCC / why does it matter?
```
