### ISSUE TITLE
View data from Kobo projects in Terraso

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#57]
#Description

#Scenario
Luis has an ongoing monitoring and evaluation process in which his team of volunteers is constantly filling out a KoBo survey providing updates on the status regeneration projects. He wants to share this information continuously with his partners so that everyone will be able to look at the data and understand the impact of his org’s activities. But downloading data from KoBo and uploading it to Terraso is time consuming. 

```[tasklist]
### Tasks
- [x] Engineering Research - How do we get data from Kobo to Terraso
```

# User Stories / Acceptance Criteria

## Product
- [ ] As a user in the Shared Files module, I want to be able to share a dataset from KoBoToolbox, so that users will be able to access the most recent  version of the data.
- [ ] After I have chosen a file, I want to be able to update the name and provide a description
- [ ] As a member of the landscape/group where the file has been shared, I want to be able to download the file in the format of my choice (JSON, Excel, CSV)

## Design
- [ ] Implementation Matches Design
- [ ] Copy Editing
- [ ] Translation
- [ ] Additional issues...

**Comment by DerekCaelin** [comment]
Closed - duplicate of https://github.com/techmatters/terraso-web-client/issues/994
