### ISSUE TITLE
Plan updates to Terraso website with LandPKS launch

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#571]
```[tasklist]
### Tasks
- [x] Document the tasks outline and roles & responsibilities
- [x] Work with Landpks team for collaborative IA work
- [x] Finish Content inventory of the current Terraso site map to the User stories by audience list (G-sheet)
- [x] Hana & Derek will work on the Minimal change proposal.
- [x] User story exercise with LPKS team once their content inventory is complete.
```
**Assets & artifacts** 
- [IA discussion (Mural) ](https://app.mural.co/t/techmatters9109/m/techmatters9109/1709659637222/2eb170955649bd1b0a5a3472010f0ec360f385c8?sender=ue3adfb39ae85b9ee50a94245)
- Marketing site update plan: [Task outlines & RACI doc](https://docs.google.com/document/d/1uX36AGJM9TfrTdXjnAxjpe_3tTwLzgzvGvj-eMmSrPw/edit#heading=h.g75xpfsj8uxs)
- [User stories for the Terraso marketing site](https://docs.google.com/spreadsheets/d/1mf2e9J_z4-m-2vOqC46KyESFU-N8fcH6DbS4GFaigBE/edit#gid=0),
- [WORK-IN-PROGRESS] [Current site update proposal ](https://app.mural.co/t/techmatters9109/m/techmatters9109/1710877455667/2b57cc3b1d8262237c56d94211cb8a6cf2b5d090?sender=ue3adfb39ae85b9ee50a94245)

Target date: Launch the new site in May/June

**Comment by Hanal-code** [comment]
[Audience and use stories (G-sheet) ](https://docs.google.com/spreadsheets/d/1mf2e9J_z4-m-2vOqC46KyESFU-N8fcH6DbS4GFaigBE/edit#gid=0)
