### ISSUE TITLE
Expose non-sensitive Terraso pages to unauthenticated users. 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#588]
## Description
In order for first-time users of Terraso to understand the value add of the tool suite, we should expose pages that explain content and functionality to unauthenticated users, with a path to account creation at the point that people understand the value-add. 

## Process
```[tasklist]
### Issues
- [ ] Product task - write spec
- [ ] Design research (if needed)
- [ ] Engineering research (if needed)
- [ ] Design task - design experience
- [ ] Team Reviews design
- [ ] Design task - Copy edits
- [ ] Engineering task - implement design
- [ ] (optional) Design tweaks based on learning
- [ ] Product tests against criteria
- [ ] Translation
- [ ] Product task - Write QA plan
- [ ] Usability testing
```

### Product
- [ ] As a non-authenticated user, I want to be able to access pages without creating an account, so I can explore the value add provided by Terraso
   - [ ] home screen
   - [ ] landscapes directory
   - [ ] landscape page (do not expose file sharing)
   - [ ] groups directory
   - [ ] groups page (do not expose file sharing)
   - [ ] tools page
   - [ ] story maps directory
   - [ ] public digital artifacts
- [ ] As a non-authenticated user, I want a pathway to account creation at the point at which I perceive there is value add for me
