### ISSUE TITLE
Review soil texture guide help text and add to Figma

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#606]
[Text on page 10. ](https://docs.google.com/document/d/1zYIfmnZSlksfbZyFE_zE61dcAo-GxTyVu3CoRevcqoU/edit?usp=sharing)

[Design pattern Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=8336-12439&t=yRVaCeOqwfOAhPFY-1)

```[tasklist]
### Tasks
- [x] Text first draft
- [x] Text final draft
- [x] Design pattern mockup
```

**Comment by CourtneyLee333** [comment]
Put some questions on the text for Laura.

**Comment by CourtneyLee333** [comment]
@DerekCaelin This particular bit of help text will go in the [hand texturing guide found here](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800%3A13900&mode=design&t=NUBjDnMi9DdPL9MP-1). This is new content that doesn't exist in the legacy app. While this is important content for users, it might not be critical for Capri. What do you think?

**Comment by CourtneyLee333** [comment]
Moving this to backlog, with Slim MVP label.

**Comment by CourtneyLee333** [comment]
@DerekCaelin This might be a good one for Paul to work on. Adding the text in the app should be a quick task. I can finalize the text and make the design pattern pretty quickly too.

**Comment by CourtneyLee333** [comment]
@paulschreiber The text is ready for your review. I'm working on design pattern now.

**Comment by CourtneyLee333** [comment]
Design pattern is ready.

**Comment by DerekCaelin** [comment]
Thanks for this, @CourtneyLee333. @paulschreiber, I made this issue of a user story and added a separate implementation task: https://github.com/techmatters/terraso-product/issues/856

**Comment by paulschreiber** [comment]
@CourtneyLee333 I left suggestions in the doc.
