### ISSUE TITLE
Update site location dashboard with revised copy

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#609]
## References
- [Copy document](https://docs.google.com/document/d/1A_EIe7C8m5h78ijz6zNUdFSsUfVFwt8vK_GsRcByXH8/edit)

```[tasklist]
### Tasks
- [x] Courtney's first draft
- [ ] https://github.com/techmatters/terraso-product/issues/633
- [ ] https://github.com/techmatters/terraso-product/issues/632
- [x] Coutney's final edits, added to Figma
```

**Comment by CourtneyLee333** [comment]
Team agreed to move forward the text in the document: Courtney will edit, final polish, and add to Figma.

**Comment by CourtneyLee333** [comment]
Need to have finalized by May beginning.
