### ISSUE TITLE
Write help content for location dashboard

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#610]
[Copy document](https://docs.google.com/document/d/1qRvfXfjKkoKAXl3jGeDwlRMXw3rYbvJc5ciY06Ehbqw/edit)

```[tasklist]
### Tasks
- [x] Courtney's first draft
- [ ] https://github.com/techmatters/terraso-product/issues/619
- [x] Coutney's final edits, added to Figma
```

**Comment by CourtneyLee333** [comment]
Need to have finalized by May beginning.

**Comment by DerekCaelin** [comment]
@hamriclr completed the review, no comments.

**Comment by DerekCaelin** [comment]
Closing as done
