### ISSUE TITLE
Write help content for Soil ID

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#611]
```[tasklist]
### Tasks
- [x] Courtney's first draft
- [x] Laura's review: https://github.com/techmatters/terraso-product/issues/620#issue-2244548586
- [x] Coutney's final edits
- [x] Add text to Figma
```

**Comment by CourtneyLee333** [comment]
Team agreed to move forward the text in the document: Courtney will edit, final polish, and add to Figma.

**Comment by CourtneyLee333** [comment]
Need to have finalized by May beginning.
