### ISSUE TITLE
Terraso Update: LandPKS - part 1

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#613]
Generate content for the the Terraso.org marketing site to include key language about LandPKS, in English and Spanish.

Derek’s Notes: 

- The audience for Terraso.org is broader than LandPKS. Terraso is marketed broadly towards people seeking a sustainable world, with a focus on nonprofits following a landscape/community based approach. Less of an interest in ESD and more of an interest in the “so what”
- Although we mention LandPKS as an app suite we will make no mention of monitoring for now
- The Terraso website could use some updating more generally but I’ve tried to constrain my edits to just adding language about LandPKS. 

## References
[Mural](https://app.mural.co/t/techmatters9109/m/techmatters9109/1710877455667/2b57cc3b1d8262237c56d94211cb8a6cf2b5d090?sender=u3faecbd439cadb255c696741)

[String changes](https://docs.google.com/document/d/1yvEqJ0dwF1R9A_MfkFE2MavGy6CFHnegERsrqiVqyng/edit?tab=t.0)

```[tasklist]
### Tasks
- [x] Review Mural board
- [x] Derek [writes new language](https://docs.google.com/document/d/1yvEqJ0dwF1R9A_MfkFE2MavGy6CFHnegERsrqiVqyng/edit?tab=t.0)
- [x] Courtney Reviews
- [x] Amaya Reviews
- [x] steve Reviews
- [ ] Translate into our supported languages
- [ ] Derek publishes updates to Terraso.org (English)
```

**Comment by DerekCaelin** [comment]
@theladymay checking in on this

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I've written [some language ](https://docs.google.com/document/d/1yvEqJ0dwF1R9A_MfkFE2MavGy6CFHnegERsrqiVqyng/edit?tab=t.0#heading=h.t6f03a1jea8) to update how we speak about LandPKS on Terraso.org, would appreciate your review.

**Comment by CourtneyLee333** [comment]
Thanks @DerekCaelin. I left comments and suggested edits.

**Comment by DerekCaelin** [comment]
Thanks @CourtneyLee333 - over to @theladymay

**Comment by DerekCaelin** [comment]
Amaya is happy with this, over to steve

**Comment by ssfrancis** [comment]
Steve has left comments in the document.  Review complete.  Back to @DerekCaelin

**Comment by DerekCaelin** [comment]
Sent new language to Julie for translation into Spanish

**Comment by DerekCaelin** [comment]
I can't preload the English string changes apparently, so I'll plan to make these updates prior to launch day Feb 8
