### ISSUE TITLE
Review Help Content for SoilID

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#620]
Review help content for SoilID [in this document](https://docs.google.com/document/d/1qRvfXfjKkoKAXl3jGeDwlRMXw3rYbvJc5ciY06Ehbqw/edit).
```[tasklist]
### Tasks
- [x] Blank Soil ID page: Soil ID description (on-page)
- [x] Blank Soil ID page: Top Soil Matches (info sheet)
- [ ] Blank Soil ID page: Notice (on-page)
- [x] Offline error message
- [x] No soil map data error message
- [x] Site Data description (on-page)
- [x] Site Data offline message (on-page)
- [x] Soil info sheet labels
- [ ] Soil Info Sheet: Location Score description (on-page)
- [ ] Soil Info Sheet: Location Score description (info sheet)
- [ ] Soil Info Sheet: Soil Properties Score (info sheet)
- [x] Rate this Soil Match menu
- [ ] None of the matches are correct
- [x] Manual soil ID / ESD entry
- [x] Selected soil indicator
- [x] Manually entered selected soil
```

**Comment by hamriclr** [comment]
Notes:
- would be good to link to the new LCC documentation when it is created on the Terraso LPKS site from the LCC item in the soil series info sheet.
- waiting on Jon review for Location Score and Soil Properties Score info sheets
- the Location Score on-page description references the soil map layers; if those aren't capri, we should edit that text.
- how many soils are we going to show the user? (legacy shows 12).

**Comment by DerekCaelin** [comment]
@CourtneyLee333 Jon has provided input on the help text, so as document owner you should be able to review and finalize changes to the copy. Please note Laura's feedback on references to "soil map layers" 

> how many soils are we going to show the user? (legacy shows 12).
@hamriclr we will show the top 4 matches and expose all twelve on user request

**Comment by CourtneyLee333** [comment]
@DerekCaelin I'm assuming that "expose all twelve on user request" is inline with the designs I made. And I also assume that all the matches, up to a max of 12, will be calculated at the same time, and that "user request" simply means tapping the button to see more matches.
