### ISSUE TITLE
Soil ID - User Manually Sets SoilID

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#634]
## Description
Allow the user to select what they believe to be the correct soil id from ranking list

## Designs

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/761
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/762
```

## Process
```[tasklist]
### Issues
- [ ] Product task - write spec
- [ ] Design research (if needed)
- [ ] Engineering research (if needed)
- [ ] Design task - design experience
- [ ] Team Reviews design
- [ ] Design task - Copy edits
- [ ] Engineering task - implement design
- [ ] (optional) Design tweaks based on learning
- [ ] Product tests against criteria
- [ ] Translation
- [ ] Product task - Write QA plan
- [ ] Usability testing
```

### Product
- [ ] User Story
- [ ] User Story
- [ ] User Story

### QA
Happy Path Test
- [ ] 
- [ ] 

Unhappy Path Test
- [ ] 
- [ ]

**Comment by DerekCaelin** [comment]
Duplicate of: https://github.com/techmatters/terraso-product/issues/659
