### ISSUE TITLE
QA - Soil color data input

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#644]
[ Soil Color Test](https://docs.google.com/spreadsheets/d/1XuqQspff4TptXOuG5UHs-i6RkRuqhrcrMqCltyqYLGo/edit#gid=2004954072)
[Google Form](https://docs.google.com/forms/d/1K5WmXpNmiUqR1sIk0_N2zKlPUEwX9PFEclk9nKh1GIY/edit#response=ACYDBNgeFSuh3XNggHfapukTGIXM26wd7tmh_xyJINd04Fpo8njlHbs4kOhRtRBI6g-VGe8)

```[tasklist]
### Tasks
- [x] Write Test
- [x] Derek tests - functional test
- [x] Courtney tests - functional test, design notes
- [x] Courtney submits notes to Derek
- [x] https://github.com/techmatters/terraso-product/issues/823
- [ ] https://github.com/techmatters/terraso-product/issues/824
- [x] log bugs from testers
```

**Comment by CourtneyLee333** [comment]
Note to self: all tests passed on Android. Need to do iOS.

Delete Data? dialog:
This will delete the previously entered soil color data for this depth interval.

**Comment by DerekCaelin** [comment]
@CourtneyLee333 Paul gave me a workaround for activating the iPhone camera if it doesn't yet have permissions
- open up the slope meter screen
- grant camera permissions there
- then go back to the color screen

But I wasn't able to test color because our method involves analyzing files from the Internet. I don't know if you have a Munsell book you could photograph directly...




[1:27](https://tech-matters.slack.com/archives/D01SAC03AK1/p1715794047487099)
open up the slope meter screen
1:27
grant camera permissions there
[1:27](https://tech-matters.slack.com/archives/D01SAC03AK1/p1715794052451239)
then go back to the color screen

**Comment by CourtneyLee333** [comment]
My feedback (excluding getting accurate results from photos):

- Delete Data? dialog needs updated text: This will delete the previously entered soil color data from this depth interval.
- Hue and Value fields squished together
- on iOS, I went to edit a manual color entry that was previously saved. I cleared the first hue field. The Done button was still enabled so I tapped it. I was returned to the soil pit screen with the previous data still showing. When I tapped the color to edit it again, the app crashed. Unfortunately I'm not sure which account entered and saved the previous data, or when. Will try to replicate.... Okay, I just did this again and notice that when I clear out the first hue field, the munsell result changes from the previous 5YR to 10R (see Slack image). When I tap Done, I'm returned to the Soil Pit screen with the 10R result showing. Tapping that color to edit it again did not crash the app. The 10R result persists. I did the test again - saved the first Hue as 5, then cleared the field - and the result this time got changed to 10RP. 
- Value fields - the entire field should be interactive, not just the down arrow. 
-
