### ISSUE TITLE
QA for selecting a location/site on the map

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#648]
[Test cases](https://docs.google.com/spreadsheets/d/1GbEEPST69IHwD_ALwFQssZZRZMJjc9V8SX4g44p2pxs/edit#gid=2004954072)

```[tasklist]
### Tasks
- [x] Derek tests
- [x] Courtney tests and sends feedback to Derek
- [x] Derek files bugs and adds P1 bugs to the parent issue
```

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/759
- [x] Select testers
- [x] Send to testers (1 week time frame)
- [x] Log bugs emerging from test
- [x] Laura Reviews
- [x] Amaya Reviews
- [x] Max Reviews
```

**Comment by CourtneyLee333** [comment]
@DerekCaelin I finished my review. I made a whole bunch of comments on the test case doc not to be overly pedantic, but to point out things that will be confusing to other testers if not clarified.

**Comment by CourtneyLee333** [comment]
(forgot to test iOS. doing that now.)

**Comment by DerekCaelin** [comment]
The outstanding bug: https://github.com/techmatters/terraso-product/issues/774
