### ISSUE TITLE
Look up soil information for a location

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#660]
The user explores information about a potential soil at a given location. If they are on a temporary location, they have a goal of learning enough to create a site location. If the user is on a site location, they are trying to determine whether the data they have  collected matches a potential soil.

## References
[Product Spec](https://docs.google.com/document/d/1vjwoSj_TwxnZELVznmPBsb2jGMCo-CuJTWSub3f0l-o/edit)
[UI elements Soil Info Sheet](https://docs.google.com/spreadsheets/d/10gAV_Ja-x7mVaZa5hzLnq_yien-qfTnwhzXJiek4aww/edit#gid=63009738)

[Mid-Level Spec](https://docs.google.com/document/d/1Yxu0Ngs7zGQSebbmRelDlXv5LjmnJAP-UrYVWdCqEGo/edit?usp=drive_link)
[Soil Help Text](https://docs.google.com/document/d/1qRvfXfjKkoKAXl3jGeDwlRMXw3rYbvJc5ciY06Ehbqw/edit)

### Dependencies
- https://github.com/techmatters/terraso-product/issues/163

### Temporary Location

[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-15906&mode=design&t=0BDLCV0uVBrsS1M9-0)

### Site location
[Figma](https://www.figma.com/file/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?type=design&node-id=5800-15155&mode=design&t=wZleLrj8STmHU9UK-0)

## Process
```[tasklist]
### Tasks
- [x] Design task - design experience
- [ ] https://github.com/techmatters/terraso-product/issues/646
- [ ] https://github.com/techmatters/terraso-product/issues/653
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1156
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1158
- [ ] https://github.com/techmatters/terraso-product/issues/700
- [ ] https://github.com/techmatters/terraso-product/issues/674
- [ ] https://github.com/techmatters/terraso-product/issues/675
- [ ] Usability testing
- [ ] Web Documentation
```

### All locations
- [ ] As a viewer, I see a page that describes, for a given soil...
   - [ ] Soil Series Name
   - [ ] Soil Component name
   - [ ] Soil Description 
   - [ ] Ecological Site Name
   - [ ] Ecological Site ID
 - [ ] As a viewer I want to see the a Soil Location Score module, so I can I compare the site info to the data in SoilWeb
- [ ] As a viewer I want to see Soil Properties (Texture, Color, Fragments)
### Temporary Location
- [ ] As a viewer, I want the option to create a site, so I can start the process of collecting data about a location. 

### Site Location

- [ ] As a manager, contributor, or viewer, I want to compare the data associated with the site location with the soil properties listed above, so I can determine whether my soil matches
- [ ] As a manager or a contributor, I want to be able to initiate the rate soils  experience

**Comment by DerekCaelin** [comment]
Closing, with the expectation that we'll do QA before full launch: 
https://github.com/techmatters/terraso-product/issues/674
https://github.com/techmatters/terraso-product/issues/675
