### ISSUE TITLE
Finish Removing Native Base

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#742]
```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1125#issue-2248634423
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1124
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/688
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1123
```

**Comment by DerekCaelin** [comment]
@shrouxm Should we close this issue?
