### ISSUE TITLE
Team Reviews design for rate my soil match - Capri experience

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#752]
Organize a discussion, share updated design with implementing team and scope the new design. 

```[tasklist]
### Tasks
- [ ] Share capri design for rate my soil match
- [ ] gather feedback and revise as necessary
- [ ] Ask engineers to size
```

**Comment by CourtneyLee333** [comment]
@DerekCaelin this issue seems unnecessary to me. Can we just move #749 through the Review column instead?

**Comment by DerekCaelin** [comment]
@CourtneyLee333 ah ok, makes sense, if the "design" task is only marked done after the review
