### ISSUE TITLE
QA login experience

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#756]
Test cases for login: [Test](https://docs.google.com/spreadsheets/d/1AnjoVZ1zqu0J7apdyzAcJNBZccgrRqacJo_XgJJZh6o/edit?gid=2004954072#gid=2004954072)

[The Google form](https://docs.google.com/forms/d/1z8bG0XAUyqyTIYcHZBFw98s8wxeahXQBK9Xj7yH-KIo/edit)

```[tasklist]
### Tasks
- [x] Derek Write tests and create google form
- [x] Courtney tests
- [ ] https://github.com/techmatters/terraso-product/issues/957
- [ ] https://github.com/techmatters/terraso-product/issues/982
```

> Combine with provide permissions and see map location

**Comment by DerekCaelin** [comment]
Sending this to @CourtneyLee333 for her formal eval.

**Comment by CourtneyLee333** [comment]
@DerekCaelin The sign-in test looks good to me. When it comes to creating the full form, how about if we combine this with the locations permission dialog and the initial map experience where one should be centered on their location?
