### ISSUE TITLE
QA Foundational Work

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#758]
Prepare our QA process with external reviewers. 

```[tasklist]
### Tasks
- [x] Recruit testers
- [x] Get email address associated with app stores
- [x] Assign to testing groups - iOS and Android
- [x] Send instructions for installing/updating application
```

**Comment by DerekCaelin** [comment]
Paul should have testing documentation.
Develop timeline for implementation. Small 30 min chunks.
