### ISSUE TITLE
Create components design documentation - July

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#762]
Start documenting these things in a Components page in the Figma file

[Courtney's Figjam](https://www.figma.com/file/1vthsuXKszE0kikBOVA4AR/LandPKS-Soil-ID-elements?type=whiteboard&node-id=0%3A1&t=NxMidp0aqcbe9SzI-1)

[Ruxandra's Figjam](https://www.figma.com/file/RJwtiehQUFy3I29d9lSrHY/Soil-Info-Sheets?type=whiteboard&node-id=0-1&t=iDiDOk8cAdxag7zF-0)

```[tasklist]
### Tasks
- [x] https://github.com/techmatters/terraso-product/issues/872
- [x] https://github.com/techmatters/terraso-product/issues/873
- [x] https://github.com/techmatters/terraso-product/issues/874
- [x] https://github.com/techmatters/terraso-product/issues/875
- [x] https://github.com/techmatters/terraso-product/issues/876
- [x] https://github.com/techmatters/terraso-product/issues/877
- [x] https://github.com/techmatters/terraso-product/issues/878
- [x] https://github.com/techmatters/terraso-product/issues/879
- [ ] https://github.com/techmatters/terraso-product/issues/880
- [x] https://github.com/techmatters/terraso-product/issues/881
- [x] https://github.com/techmatters/terraso-product/issues/882
- [ ] https://github.com/techmatters/terraso-product/issues/884
- [ ] https://github.com/techmatters/terraso-product/issues/885
- [ ] https://github.com/techmatters/terraso-product/issues/886
- [ ] https://github.com/techmatters/terraso-product/issues/887
- [ ] https://github.com/techmatters/terraso-product/issues/889
- [ ] https://github.com/techmatters/terraso-product/issues/890
- [ ] https://github.com/techmatters/terraso-product/issues/883
- [ ] https://github.com/techmatters/terraso-product/issues/898
- [ ] https://github.com/techmatters/terraso-product/issues/946
- [ ] design general screen styling and spacing component
- [ ] Design Check box component
- [ ] Design Bulleted and Numbered Lists components
- [ ] Design dialog box component
```

**Comment by CourtneyLee333** [comment]
@DerekCaelin FYI I broke this down into single issues.
