### ISSUE TITLE
Soil Info - Soil Map Explorer

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#768]
Display a Soil Map in the Location Score module, so that soil scientists can explore nearby soils.

## References
Dependent on #44 

[Garo 11/29/2023](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN?node-id=3803-23430#630946677): "assuming we've already implemented the data layers, we can just drop in the same component as the dashboard with the data layer's style enabled."

## Designs
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=3803-23430&t=nIiJTJshDPZ5i7Wb-0)

#### Design as of 5/9/2024, see figma for most recent version
![Image](https://github.com/techmatters/terraso-product/assets/10799815/4f590bff-2030-4a00-a15b-2a0de3622b00)

```[tasklist]
### Tasks
- [ ] Design finished
- [ ] Engineering reviews Design
- [ ] Add Soil Map to Soil Info location score module
```

## Acceptance Criteria
- [ ] As any logged in user, I can see a soil map in the location module, so I can explore the local data myself
- [ ] I see a text call to action to explore the data layer on the home screen
