### ISSUE TITLE
Use LandPKS Offline

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#792]
While offline, allow the user to create, edit, and delete sites and projects, and to collect data, while receiving the correct indicators.

```[tasklist]
### User Stories
- [ ] Collect data offline
- [ ] Manage projects offline
- [ ] Offline notifications
- [ ] Resync data when back online
```
