### ISSUE TITLE
Notify users of server-side changes

### ISSUE THREAD

**Issue by ltseng** [techmatters/terraso-product#794]
This will require a bit of research. We need to figure out a way to avoid client devices having to ping the Terraso server every minute to check for new data, ideally. 

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/486
- [ ] https://github.com/techmatters/terraso-product/issues/487
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1362
- [ ] https://github.com/techmatters/terraso-product/issues/807
```

**Comment by DerekCaelin** [comment]
We don't currently plan to do this
