### ISSUE TITLE
Design experience for offline users

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#805]
Update the design for the experience for users who are offline. Consider [offline notifications, warnings, and signifiers](https://github.com/techmatters/terraso-product/issues/793) and [how the client behaves](https://github.com/techmatters/terraso-product/issues/523) (what should the user be able to? what should the user be prevented from doing?)

## References
- https://github.com/techmatters/terraso-product/issues/523
- https://github.com/techmatters/terraso-product/issues/793

## Acceptance Criteria
- Updated designs for offline users
- Think through all instances where the client will want to call information from the server
```[tasklist]
### Tasks
- [ ] Sign In
- [ ] Map
- [ ] Temporary Location
- [ ] Site Location popover and dashboard
- [ ] Sites List
- [ ] Create Site
- [ ] Site Settings
- [ ] Unaffiliated Site Dashboard
- [ ] Unaffiliated Site data collection
- [ ] Unaffiliated Site Soil ID
- [ ] Affiliated Site Dashboard
- [ ] Affiliated Site data collection
- [ ] Affiliated Site Soil ID
- [ ] Project Management - Create Project
- [ ] Project Management - Inputs tab
- [ ] Project Management - Sites tab
- [ ] Project Management - Team tab
- [ ] Project Management - Settings tab
- [ ] App Settings screen
```

**Comment by CourtneyLee333** [comment]
@DerekCaelin What's up with this issue? Can it be closed?

**Comment by DerekCaelin** [comment]
Seems old and the work is better captured in in https://github.com/techmatters/terraso-mobile-client/issues/2372 - closing.
