### ISSUE TITLE
Migrate ILM Practical Guide from terraso.org to landscapes.global

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#84]
```[tasklist]
### Tasks
- [x] Get paul access to landscapes.global
- [x] Export practical guide (data, plugins, css, etc etc)
- [x] Import to landscapes.global
- [ ] Redirect links on our own website to landscapes.global page
- [ ] Landscapes.global team: Make sure analytics are in place.
```
