### ISSUE TITLE
Add partner logos to landpks site

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#911]
Assemble partner logos for LandPKS.

## References
- [LandPKS Website](https://landpks.terraso.org)
- [LandPKS marketing site google doc](https://docs.google.com/document/d/1J0IHP4gHxakHcvHKDD6qNMOyrk7HRasjpvUdrrU5cDg/edit?disco=AAABNtYgVAU)
- [LandPKS legacy partners](https://landpotential.org/about/partners/)
- [Drive](https://drive.google.com/drive/u/0/folders/11oSPm0bzJxbmqgQ0fmLTOmEUYWPvW449)

```[tasklist]
### Tasks
- [x] Become an editor for the landpks site
- [x] Find logos for all partners not already listed, ideally in SVG format
- [x] Make a grid of logos (no categories or names) that takes up as little vertical space as possible
```

**Comment by DerekCaelin** [comment]
@theladymay What's the status of this?

**Comment by DerekCaelin** [comment]
@paulschreiber have you heard back from the various orgs without SVGs? Are we ok to build the grid?

**Comment by paulschreiber** [comment]
@DerekCaelin we received one additional logo. We can go ahead and start building. What order should the logos be in?

**Comment by paulschreiber** [comment]
@DerekCaelin this is ready for review.

**Comment by DerekCaelin** [comment]
@paulschreiber thank you! I see some distortion in logos:



![Image](https://github.com/user-attachments/assets/85182bd2-d806-4175-a38d-99b18ea09941)
![Image](https://github.com/user-attachments/assets/0bc0386d-8b3b-48a5-8b98-1a94931d9f40)
![Image](https://github.com/user-attachments/assets/8c1f02f0-c145-46bb-b459-d94fcc454807)

**Comment by paulschreiber** [comment]
@DerekCaelin Must be browser-specific. Can't reproduce in Chrome 128, Safari 17.6 or Firefox 129. Where are you seeing this?

**Comment by paulschreiber** [comment]
Seems fine in v1.69.160.

**Comment by DerekCaelin** [comment]
It seems to happen when I change my window width. This is showing up in Chrome 128.0.6613.114 and Firefox 129.0.2

**Comment by paulschreiber** [comment]
@DerekCaelin I can reproduce with a very narrow viewport. Had you included this information (and a full window screen shot) previously, we could have resolved this much more quickly.

**Comment by paulschreiber** [comment]
This is fixed.
