### ISSUE TITLE
Jessica Reing  - Usability study 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#919]
```[tasklist]
### Tasks
- [x] Conduct the usability study with Jessica
- [ ] https://github.com/techmatters/terraso-product/issues/920
- [ ] https://github.com/techmatters/terraso-product/issues/921
```
