### ISSUE TITLE
Write Documentation - Creating an account and signing in

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#927]
[Documentation to review](https://docs.google.com/document/d/1aMfx_RXecn5ZbVehyf7N99Q8Dx4B-vpBBCOKQvg09nA/edit)

## References
[Editorial Guide](https://docs.google.com/document/d/1txlmcir4Ri4CK-DlGOujN7k5PN4cwi5z5SI_P09sh2s/edit#heading=h.7spetqy7l2qe)
[Glossary of terms](https://docs.google.com/document/d/1txlmcir4Ri4CK-DlGOujN7k5PN4cwi5z5SI_P09sh2s/edit#heading=h.2prb5lex1pbt)

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1aMfx_RXecn5ZbVehyf7N99Q8Dx4B-vpBBCOKQvg09nA/edit)
- [x] Review by Derek
- [x] Review by Paul
- [x] Create page on staging site
- [ ] Send to Spanish translator
```

**Comment by hamriclr** [comment]
@DerekCaelin Ready for review

**Comment by DerekCaelin** [comment]
@paulschreiber We are starting to write documentation for LandPKS. Please review. I've attached the style guide and glossary of terms for reference. Audience: LandPKS users

**Comment by DerekCaelin** [comment]
@CourtneyLee333 I thought you'd want to see this - I copied the documentation into the staging LandPKS site. https://landpks-terraso-staging.mystagingwebsite.com/soil-id-help-documentation/getting-started/create-account/

Just a note, it looks like there's an issue with styling? I see a space between an image and a header in the editor which does not appear when the page is published. 

## editor
<img src="https://github.com/user-attachments/assets/d2765c09-48aa-48f0-9e2b-b211ff8a2b6d" width = "300px">

## live
<img src="https://github.com/user-attachments/assets/7b83cdcb-458e-4ba2-af6d-15961e45bd65" width = "300px">

**Comment by CourtneyLee333** [comment]
@DerekCaelin I see a few things that could be improved:
- I think it's important to talk about creating an account, not just signing in. As in, what is Terraso and what does it mean to create a Terraso account in order to use Soil ID?
- Adding a paragraph break after that image will give it space beneath. I did that so you can see. 
- Some of the headings have all words capitalized and some don't. Let's get consistent.

**Comment by DerekCaelin** [comment]
Pulling this into August as there's additional work to do.

**Comment by DerekCaelin** [comment]
Updated and closed.
