### ISSUE TITLE
Write Documentation - Using the map 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#928]
Write web documentation for how to use LandPKS Map function. (Includes Temporary Pin and Temporary Pin Dashboard)
```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1m-9Neg4fq0bV37-B26JCxJV562Ff4Cx8yLY-3H37gXA/edit)
- [x] Review by Derek
- [x] Review by Paul
- [x] Create page on landpks.terraso.org
- [ ] Send to Spanish translator
```

**Comment by hamriclr** [comment]
@DerekCaelin ready for review

**Comment by DerekCaelin** [comment]
@paulschreiber This looks good to me. Please review. This is documentation for the LandPKS website, audience is a landpks user. Please reassign to me once finished.

**Comment by hamriclr** [comment]
@DerekCaelin this is the one we looked at that needed some additional edits. I think it is good for review now.
