### ISSUE TITLE
Write Documentation - User Roles

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#929]
Write web documentation explaining the permissions and functions of User Roles (Manager, Contributor, Viewer). 
```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1xe7O6LEzNXaMyzP0OyDQXMz7nJLTRyETywlsweSgFBs/edit)
- [ ] Review by Derek
- [ ] Review by Paul
- [ ] Create page on landpks.terraso.org
- [ ] Send to Spanish translator
```

**Comment by DerekCaelin** [comment]
Now Duplicate of https://github.com/techmatters/terraso-product/issues/1066
