### ISSUE TITLE
Write Documentation - Creating Sites

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#930]
Write documentation on how to create sites. Mark connections to related articles (like temporary pins). Include section on Sites list. 

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1IAIC_M4htR9R9GQa9h_pat6x21RGufP0G9x7IyRbIrE/edit)
- [x] Review by Derek
- [x] Review by Paul
- [x] transfer content on landpks.terraso.org
```
**Wordpress**
[Creating sites](https://landpks.terraso.org/wp-admin/post.php?post=1379&action=edit)
[Accessing Sites](https://landpks.terraso.org/wp-admin/post.php?post=1457&action=edit)

**Comment by DerekCaelin** [comment]
This appears to be done https://landpks-terraso-staging.mystagingwebsite.com/soil-id-help-documentation/sites/creating-a-site/

**Comment by DerekCaelin** [comment]
Not actually done: content is here: https://docs.google.com/document/d/1IAIC_M4htR9R9GQa9h_pat6x21RGufP0G9x7IyRbIrE/edit#heading=h.ysyxhucpnrpi

**Comment by DerekCaelin** [comment]
Over to @paulschreiber

**Comment by DerekCaelin** [comment]
future improvement, link to site dashboard page once that is ready
