### ISSUE TITLE
Write Documentation - Soil Identification and Ecological Site

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#931]
Write documentation introducing the topics of Soil ID and Ecological Site. Ideas for article: where are Soil ID and ESD are found, what do they describe, how to interpret the results. Mark links to related concepts (eg, various data inputs)

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1xrmLh5-RTNBETNvJLrRCFO9ZlX8piBNmnpKa-lAOejM/edit)
- [x] Review by Derek
- [x] Review by Paul
- [x] transfer content on landpks.terraso.org
```
