### ISSUE TITLE
Write Documentation - Slope 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#932]
Write documentation for slope (include steepness and slope modules)

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1u4G6FNp0Fp_gMklj5HNoJjpQHGDir9nsK4tQ1urAUTA/edit)
- [x] Review by Derek
- [x] Review by Paul
- [x] transfer content on landpks.terraso.org
```

**Comment by DerekCaelin** [comment]
Over to you @paulschreiber. This is documentation for general audience.

**Comment by DerekCaelin** [comment]
Quick followup question for @paulschreiber in the doc.
