### ISSUE TITLE
Write Documentation - Soil Texture and Rock Fragment

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#934]
Write documentation on the Soil Texture and Rock Fragment module. 

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1u52xzJ81nJBZaQWx5ApZsbxefyywrGJdiFZI4cW_Dwk/edit)
- [x] Review by Derek
- [x] Review by Paul
- [x] transfer content on landpks.terraso.org
```

**Comment by DerekCaelin** [comment]
I've included language from the app explaining what texture and rock fragments are, and how to measure them.

**Comment by DerekCaelin** [comment]
Over to @paulschreiber
