### ISSUE TITLE
Write Documentation - Soil Color

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#935]
Write documentation for the Soil Color module. 

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1DLVHLO6J0xC1YHw0dpUyhOHKDooSgYtdx1mFbRXaErw/edit#heading=h.3sp50qk1y6fe)
- [x] Review by Derek
- [x] Review by Paul
- [x] transfer content on landpks.terraso.org
```

**Comment by DerekCaelin** [comment]
Over to @paulschreiber
