### ISSUE TITLE
Write Documentation - Notes

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#937]
Write documentation for the Notes module. 

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1vXAJuE6o01-2-vFGoRKd67DtyDxOmE0n9LdEavNp5N8/edit)
- [x] Review by Derek
- [x] Review by Paul
- [x] transfer content on landpks.terraso.org
```

**Comment by DerekCaelin** [comment]
This looks good to me, over to @paulschreiber
