### ISSUE TITLE
Write Documentation - Project Inputs Tab 

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#938]
Write documentation on the Project Inputs Tab. (Include sections on data privacy, soil pit depths, data collection requirements)

```[tasklist]
### Tasks
- [ ] write [documentation](https://docs.google.com/document/d/1F88dmo2KnrBM9i8UV_BqA2v1GxjYUF0HZWAI94iv0Ao/edit)
- [ ] Review by Derek
- [ ] Review by Paul
- [ ] transfer content on landpks.terraso.org
- [ ] Send to Spanish translator
```
