### ISSUE TITLE
Write Documentation - Add sites to projects

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#939]
Write documentation on Add sites to projects

```[tasklist]
### Tasks
- [x] Derek writes [documentation](https://docs.google.com/document/d/1usCda-D0YnYiWO83s6o-DRiK6wvaW_U4GshYJaJ5-W0/edit)
- [x] Review by Courtney
- [x] Review by Paul
- [ ] transfer content on landpks.terraso.org
```

**Comment by DerekCaelin** [comment]
Not sure this is relevant given the material covered in other sections

**Comment by DerekCaelin** [comment]
duplicate of #1099
