### ISSUE TITLE
Write Documentation - Project Team

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#940]
Write documentation on Project Team (include section on inviting and managing team members)

```[tasklist]
### Tasks
- [x] Derek writes [documentation](https://docs.google.com/document/d/1wCLifw-AdOq41X7uTRcuPZMq8_gKyEbbwSeWjfzDWCU/edit)
- [x] Review by Courtney
- [x] Review by Paul
- [ ] transfer content on landpks.terraso.org
- [ ] Send to Spanish translator
```
