### ISSUE TITLE
Write Documentation - Project Inputs

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#941]
Write documentation on Project Inputs

```[tasklist]
### Tasks
- [x] derek writes [documentation](https://docs.google.com/document/d/1hdd-xddCzMoFM-WFI250q7oe1ykWNl8CLk7mwziJIR0/edit)
- [x] review by courtney
- [x] Review by Paul
- [ ] transfer content on landpks.terraso.org
```
