### ISSUE TITLE
Write Documentation - Data Privacy

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#942]
Write Documentation on Data Privacy

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1pwq4LWSLqWo9RbHMP1lQGLilnt1XbEIM6fhdPkwgr-A/edit)
- [x] Review by Derek
- [x] Review by Paul
- [x] Review by Steve
- [x] Review by Courtney
- [ ] transfer content on landpks.terraso.org
```
