### ISSUE TITLE
Write Documentation - Delete Account

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#943]
Write documentation on deleting an account:

[Relevant product spec](https://docs.google.com/document/d/18t3V8KWm1wft7K66f91wwKfUQdwIQqJonFJszGaHGeM/edit#heading=h.54w02ys7n8ko)

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/1KPh29V4iTKfrmP9dqQlh7CbXBYDuBiwhvcI92dqd-W0/edit)
- [x] Review by Derek
- [x] Review by Paul
- [ ] transfer content on landpks.terraso.org
```

**Comment by DerekCaelin** [comment]
Over to @paulschreiber
