### ISSUE TITLE
Write Documentation - Site Dashboard

### ISSUE THREAD

**Issue by hamriclr** [techmatters/terraso-product#945]
Write documentation introducing the topics of the Site Dashboard

```[tasklist]
### Tasks
- [x] write [documentation](https://docs.google.com/document/d/14E-SjU5gbHruXlw4km3nRCfe6UIv319YE8zMQAi11XM/edit)
- [x] Review by Derek
- [x] Review by Paul
- [x] transfer content on landpks.terraso.org
```

**Comment by DerekCaelin** [comment]
Over to @paulschreiber
