### ISSUE TITLE
Offline MVP research planning

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#948]
Plan engineering tasks to close our knowledge gap for implementing offline MVP.

We now have a sense of the MVP, but we lack the know-how to implement those experience. Fundamental research required.

This reflects an initial research phase. After the shareback sessions, we will plan next steps. (More research? Product spec?)

## References
[Draft Research Questions Doc](https://docs.google.com/document/d/1XTWcpsy0TiNQWM6BsBxyu-B6S3N8BxeJYWpm1TgfFi8/edit)
[LandPKS Offline Resources Page](https://docs.google.com/document/d/1-b533QRzrLM8Sba7EyiIg130wChgshKPyGe0J6d0HM8/edit#heading=h.fjxdb1ai1oji)

[Feature prioritization](https://docs.google.com/spreadsheets/d/1R2L665BzBcVrJq_lcCJXLaAHLX90pq5vdGXO1FcV-NU/edit?gid=193459743#gid=193459743)
[Rocky workflow](https://app.mural.co/t/techmatters9109/m/techmatters9109/1718284949433/4687270dbbe0bb3f15e98e2ca0c16ee358ff8e45?wid=0-1721249532426)
[Offline Syncing Scenarios](https://app.mural.co/t/techmatters9109/m/techmatters9109/1718201688620/6fda9e75f14b7b3ca9aa614647d6cb278a8a4736?wid=0-1718891919555)
[Product Spec - LandPKS Offline](https://docs.google.com/document/d/1cy2hvrfvm5pf01xCfz-i7ljCba3N3h5VQyn4Vq1b7ik/edit#heading=h.54w02ys7n8ko)

### Engineering
- [ ] Read up on on the fundamentals of offline apps (including conflict management, look at specific examples, look at the readings suggested by Steve
- [ ] Exchange and synthesize for a sharing sessions on or before Aug 6
- [ ] @paulschreiber attends Expo office ours to identify open or closed source apps that might be exemplars

### Design/Product
- [ ] Research other offline apps, look at good examples
- [ ] Draw up sample workflows, requirements docs, fatmarker sketches 
- [ ] Exchange and synthesize for a shareback session on or before August 6

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/892
```

**Comment by DerekCaelin** [comment]
Duplicate now of research tasks currently planned for sprint
