### ISSUE TITLE
Update Story Map instructions

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#953]
Update our story map instructions to reflect the new experience.

## References
[English Draft](https://docs.google.com/document/d/1XEG-feSv4fAje2JL7Bf-y-9suOmlrJyZIb28QJw4SMY/edit)

## Tasks
- [x] Write new draft
- [x] Amaya/Steve edit
- [x] Paul Edits
- [x] Update website (english)
- [x] Send to translator for Spanish
- [x] Update website (spanish)

**Comment by DerekCaelin** [comment]
Amaya reviewed - over to Paul

**Comment by paulschreiber** [comment]
I made some comments and suggestions.

**Comment by DerekCaelin** [comment]
Thanks, Paul!

**Comment by DerekCaelin** [comment]
Translation complete: https://terraso.org/es/ayuda/como-hacer-un-mapa-de-la-historia/
