### ISSUE TITLE
UI update - inputs/data terminology update

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#954]
To avoid confusion for users for whom "inputs" refers to things like soil amendments or livestock feed, we will replace the term with less confusing language.

## Designs
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10731-12905&node-type=section&t=Qqa0NUYJwdrkxrVV-0)

## Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/967
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1855
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2398
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2466
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2465
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2464
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2467
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2468
- [ ] https://github.com/techmatters/terraso-product/issues/1150
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2469
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2473
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2474
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2517
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2472
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2790
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2791
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2792
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2793
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2794
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2795
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2796
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/2797

**Comment by CourtneyLee333** [comment]
@DerekCaelin I propose we try for this in Nov or Dec if possible.

**Comment by DerekCaelin** [comment]
Scheduled them for December

**Comment by CourtneyLee333** [comment]
Reopening as I'd like to review this work for accuracy.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Quite a few sections in the [Figma page](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10731-12543&t=sNhT7sbstIF55NrD-1) got omitted from this issue:
- Site Creation, Site Settings, Site Soil ID
- Site Slope, Site Soil Tab
- Temp Location Dashboard

**Comment by DerekCaelin** [comment]
@CourtneyLee333 Thanks for flagging outstanding changes. I've filed new issues and attached them to the story above, scheduled for Feb. @paulschreiber if you do finish with launch milestone tasks, it's be great if you wanted to take these on.

**Comment by CourtneyLee333** [comment]
Thank you!
