### ISSUE TITLE
Update Figma designs with new data/observations terminology

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#967]
This is a task to refine the verbiage throughout the app in terms of how we talk about site data, soil match data, inputs, measurements, and observations. These are the intentions:

- What we've been calling site "inputs" needs to become "observations".
- On a soil info sheet, we will continue with "data".
- Clarify the soil properties table on soil info sheet like “Yemassee Soil Properties” heading.
- Nix the “Top” Soil Matches.
- Change the button to Add/Enter/Record Soil Properties.
```[tasklist]
### Tasks
- [x] Find all the screens in Figma that need changes and duplicate them on a new page
- [x] Change the verbiage as appropriate and clearly mark it up for engineers
- [ ] Apply the finalized verbiage to the Post-Capri page
```
[Figma page "Data terminology updates"](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10731-12543&t=laILdidNzZdMPc7j-1) note: changes are marked in red text, and only affected screens and components are included.

**Comment by CourtneyLee333** [comment]
@DerekCaelin FYI this issue exists. Will you make a counterpart for implementation?

**Comment by DerekCaelin** [comment]
This is now tracked by #954 and will be implemented by https://github.com/techmatters/terraso-mobile-client/issues/1855

**Comment by CourtneyLee333** [comment]
We need to talk to engineers about how to handle the Figma aspect, since there are many affected screens that already have unimplemented design updates.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Please review this and let me know what you think. If you approve, I'll apply these same text updates to the Post-Capri page designs as well. 

In terms of task management, I can see creating one task for all the changes on the "Data terminology updates" page in Figma, or break it down into a task for each section of the page. (As opposed to a single task for every edit.)

**Comment by DerekCaelin** [comment]
I think these look great. Agreed - a single issue with data terminology updates is probably the most efficient.

**Comment by DerekCaelin** [comment]
Here is an issue tracking all the changes: https://github.com/techmatters/terraso-product/issues/1142
