### ISSUE TITLE
Usability tests for August

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/terraso-product#977]
Recruit, schedule, and facilitate 2-4 First Impressions Usability Tests. 

Candidate outreach:

- [x] Martin and Grace, Ranchers Stewardship Alliance
- [x] Efraim Acosta, Pronatura
- [x] Josh Beniston, NRCS
- [x] Michael Eggen, U of Colorado (asked Laura to connect us)
```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/1001
- [ ] https://github.com/techmatters/terraso-product/issues/1014
```

**Comment by CourtneyLee333** [comment]
Efraim from Pronatura is willing to test the US version of Soil ID.
