### ISSUE TITLE
Soil ID screen - Soil Cracking Module

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#979]
Create a module on the Soil ID page to display Soil Cracking, which is relevant for the Soil ID algorithm.

## Design
[Figma](https://www.figma.com/design/KMJbhjVyrrLFHj6jGcX9lN/LandPKS-Design-Prototype-working-file?node-id=10962-8287&t=fcyACT7ReWehB7l3-1)

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/980
- [ ] https://github.com/techmatters/terraso-mobile-client/issues/1888
```

## Acceptance Criteria
- [ ] As a user looking at a site's soil ID, I should see user-generated observations on soil cracking, so I can see the information that is relevant for the Soil ID algorithm
- [ ] As a user looking at a site's soil ID, I should see a call to action to submit soil cracking information if there are are not observations yet provided.
