### ISSUE TITLE
Create components design documentation - November

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-product#986]
Start documenting these things in a Components page in the Figma file

Continuation of effort from: https://github.com/techmatters/terraso-product/issues/762

[Courtney's Figjam](https://www.figma.com/file/1vthsuXKszE0kikBOVA4AR/LandPKS-Soil-ID-elements?type=whiteboard&node-id=0%3A1&t=NxMidp0aqcbe9SzI-1)

[Ruxandra's Figjam](https://www.figma.com/file/RJwtiehQUFy3I29d9lSrHY/Soil-Info-Sheets?type=whiteboard&node-id=0-1&t=iDiDOk8cAdxag7zF-0)

```[tasklist]
### Tasks
- [ ] https://github.com/techmatters/terraso-product/issues/946
- [ ] https://github.com/techmatters/terraso-product/issues/991
- [ ] Design dialog box component
- [ ] design general screen styling and spacing component
- [ ] Design Check box component
- [ ] Design site popover component
- [ ] Design temporary location popover component
- [ ] design site cluster select component
- [ ] design site card component
- [ ] design project card component
- [ ] design notes component
- [ ] Design pinned notes component
```

**Comment by CourtneyLee333** [comment]
Holding off during August sprint while engineering catches up.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Holding off again during September.

**Comment by CourtneyLee333** [comment]
Closing this issue, as I've transferred the tasks to https://github.com/techmatters/terraso-product/issues/827
